using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SellCar
{
    public class Car
    {
        /* Đừng xoá
        public string Manu { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public string Classify { get; set; }
        public string Engine { get; set; }
        public string Transmission { get; set; }
        public string FuelType { get; set; }
        public string Price { get; set; }
        public string Picture { get; set; }
        public string Decribe { get; set;  }

        public Car(string Manu, string Model, string Color, string Classify, string Engine, string Transmission, string FuelType, string Price, string Picture, string Decribe)
        {
            this.Manu = Manu;
            this.Model = Model;
            this.Color = Color;
            this.Classify = Classify;
            this.Engine = Engine;
            this.Transmission = Transmission;
            this.FuelType = FuelType;
            this.Price = Price;
            this.Picture = Picture;
            this.Decribe = Decribe; 
        }
        */
        //

        public string[,] NewCarInfo = new string[,]
        {
            {"Manu","Model","Color","Classify","Engine","Transmission","Fuel Type","Price","Picture","Decribe"},
            {"Ferrari","F8","Vàng","Convertable","3.9L V8 Turbo","Automatic","Gas","$278,030","/image/car/Ferrari/F8/","Ferrari F8 là một cỗ máy hướng tới hiệu suất có nguồn gốc sâu xa từ xe đua và sự sang trọng. Thiết kế chắc chắn sẽ thu hút sự chú ý ở bất cứ đâu trong khi thẻ giá đảm bảo mức độ độc quyền nhất định."},
            {"Ferrari","SF90 Stradale","Đỏ","Coupe","Plug-In Hybrid 4.0L V8 Turbo","Automatic","Premium Unleaded","$649,236","/image/car/Ferrari/SF90 Stradale/","Bản xem trước về thế hệ siêu xe tiếp theo sắp ra mắt tại Marinello, Ý, Ferrari SF90 Stradale là một sự tiến hóa trong cách điện có thể khai thác mã lực một cách liền mạch để nâng cao trải nghiệm lái xe. Đây là một trong những chiếc xe tăng tốc nhanh nhất và xử lý tốt nhất trên đường, với sức mạnh điện tức thời và hệ dẫn động 4 bánh bền bỉ. Nó không có tiếng xả ly kỳ như động cơ V12 cổ điển của Ferrari, và không gian chứa đồ nhỏ ngay cả theo tiêu chuẩn siêu xe. Bỏ qua những lời chỉ trích nhỏ, SF90 Stradale là một kỳ quan công nghệ đáng kinh ngạc và là một trong những chiếc xe đường trường nhanh nhất hiện có."},
            {"Kia","Sedona","Đen","Hatchbacks","3.3L V6","Automatic","Regular Unleaded","$34,875","/image/car/KIA/Sedona/","Đối với những người TIỀN sắm trên thị trường cho một chiếc xe tải nhỏ thân thiện với ngân sách sẽ đánh giá cao Kia Sedona. Nó đi kèm với một động cơ V6 mạnh mẽ, mượt mà và dễ dàng chở tám người và đồ đạc của họ. Sedona có kiểu dáng bên ngoài đẹp trai mang lại vẻ thể thao hơn so với các đối thủ cạnh tranh, mặc dù cabin thông thường hơn. Tuy nhiên, nó rộng rãi và thoải mái, với các nút điều khiển dễ truy cập và nhiều tính năng tiêu chuẩn. Công nghệ ấn tượng nhất nằm trong trang trí SX đắt tiền, mức giá phù hợp với đề xuất giá trị của Sedona. Tuy nhiên, người lái xe sẽ đánh giá cao cửa trượt điện kép, ứng dụng điện thoại thông minh và phạm vi bảo hành đáng kể đi kèm với mỗi chiếc Sedona mới."},
            {"Kia","Seltos","Gold","Hatchbacks","2.0L I4","Automatic","Gas","$23,165","/image/car/KIA/Seltos/","Kia Seltos cung cấp một trong những thiết kế thời trang nhất trong danh mục của nó, và nền tảng hiện đại của nó đảm bảo một chuyến đi tuân thủ và thoải mái. Turbo tăng tốc nhanh chóng mà không ảnh hưởng nhiều đến hiệu quả và hệ thống hỗ trợ người lái gần như đạt tiêu chuẩn giúp mang lại sự an tâm hơn trước khi đường đi trở nên quá khó khăn. Một số đối thủ cạnh tranh cung cấp nội thất cao cấp hơn và tính linh hoạt, nhưng một số ít có thể phù hợp với sự hiện diện trên đường của Seltos về mức giá."},
            {"Kia","Soul","Đỏ","Hatchbacks","2.0L I4","Manual","Gas","$18,765","/image/car/KIA/Soul/","Kia Soul là sự lựa chọn tuyệt vời cho nhiều đối tượng khách hàng, từ gia đình nhỏ đến người đi làm, những người muốn một thứ gì đó khác biệt so với một chiếc xe cỡ nhỏ thông thường. Hệ thống truyền động hiệu quả của nó mang lại sức mạnh tốt và khả năng xử lý nhanh nhẹn, trong khi nội thất rộng rãi hơn các đối thủ và có nhiều tính năng sẵn có. Kiểu dáng cabin rất thú vị mà không ảnh hưởng đến tính thực dụng. Apple CarPlay và Android Auto là tiêu chuẩn, và hệ thống âm thanh Harman Kardon có sẵn có lưới loa LED. Với mức giá từ 17.500 đến 28.000 đô la, Soul là một lựa chọn tuyệt vời cho những người TIỀN sắm muốn có nhiều giá trị và điều đó được củng cố bởi thời gian bảo hành tiêu chuẩn kéo dài. Cơ sở trang trí thiếu nhiều tính năng, nhưng tất cả các trang trí khác đều được trang bị một cách hào phóng. Kia Soul mang đến nhiều điểm mạnh cho xe cỡ nhỏ trong một gói trang bị tổng thể quyến rũ, thú vị và đặc biệt.",},
            {"Land Rover","Defender","Trắng","SUV","2.0L I4 Turbo","Automatic","Gas","$47,774","/image/car/Land Rover/Defender/","Land Rover Defender vẫn là một trong những chiếc SUV đáng mơ ước nhất trong nhiều thập kỷ. Sự hiếm có của nó ở Hoa Kỳ chỉ làm tăng thêm sức hấp dẫn của nó. Vào năm 2020, Defender cuối cùng đã được phổ biến rộng rãi trên các bờ biển của Hoa Kỳ. Kiểu dáng nổi tiếng của nó truyền đạt những ý định chắc chắn của nó, không cái nào trong số đó đã biến mất theo chi phí của công nghệ. Trên thực tế, Defender mới là một kho tàng ma thuật cơ khí off-road, được trang bị hệ thống quản lý lực kéo thông minh nhất trên thị trường. Không giống như những chiếc Defenders trước đây, chiếc mới có bộ hệ thống an toàn cho người lái tiêu chuẩn và cabin yên tĩnh, tinh tế. Chuyến đi êm ái và thoải mái trên những con đường trải nhựa. Land Rover cung cấp một số trang bị và gói tùy chọn để đáp ứng nhu cầu của khách hàng, mặc dù những thứ đó có thể nhanh chóng tăng giá. Land Rover Defender tiếp tục là biểu tượng của sự nhạy bén và khám phá mọi địa hình, giờ đây đã có sẵn với nhiều cải tiến trên đường trường hơn bao giờ hết."},
            {"Land Rover","Discovery","Đen xám","SUV","3.0L V6 S/C","Automatic","Gas","$53,650","/image/car/Land Rover/Discovery/","Land Rover Discovery là một chiếc SUV hạng trung hướng đến những người muốn một chiếc xe địa hình có khả năng vượt trội với nội thất ba hàng ghế sang trọng. Land Rover ban đầu ra mắt Discovery vào năm 1989. Thế hệ thứ 5 hiện tại bắt đầu với mẫu 2017.",},
            {"Land Rover","Discovery Sport","Đen xám","SUV","2.0L I4 Turbo","Automatic","Gas","$42,950","/image/car/Land Rover/Discovery Sport/","Land Rover nổi tiếng với việc chế tạo những chiếc SUV sang trọng chắc chắn, và Discovery Sport chắt lọc những đặc điểm này thành một gói nhỏ gọn, nhanh nhẹn. Khoảng sáng gầm xe cao và hệ dẫn động bốn bánh giúp xe vượt qua những cung đường khó hơn so với các đối thủ cạnh tranh, trong khi hành khách bên trong được tận hưởng một cabin rộng rãi với ghế da, hệ thống kiểm soát khí hậu hai vùng và công nghệ hỗ trợ người lái. Một số đối thủ lái xe thể thao hơn, nhưng ít đối thủ cung cấp sự pha trộn giữa các kỹ năng địa hình và địa hình của Land Rover.",},
            {"Lexus","ES","Xanh dương","Sedan","3.5L V6","Automatic","Gas","$41,025","image/car/Lexus/ES/","Lexus ES là một chiếc sedan hạng sang hạng trung với cảm giác lái êm ái và cabin sang trọng được xây dựng để tạo sự thoải mái. Ba loại động cơ có sẵn, bao gồm động cơ hybrid êm ái và nội thất lớn là một trong những động cơ tinh tế nhất trong phân khúc. Tất cả các thiết bị hỗ trợ lái xe an toàn chính đều là tiêu chuẩn và dễ sử dụng. Các trang bị phía trên có các tính năng như vô lăng sưởi và cốp điện rảnh tay. Trong khi nhiều đối thủ cố gắng trở thành những chiếc sedan thể thao, Lexus ES lại ưu tiên sự thoải mái tuyệt đối.",},
            {"Lexus","IS","Đỏ","Sedan","2.0L I4 Turbo","Automatic","Gas","$40,075","image/car/Lexus/IS/","Chiếc sedan hạng sang nhỏ gọn Lexus IS là một người lái xe vui vẻ, thiết thực hàng ngày. Với công suất lên đến 311 mã lực và hệ thống treo trước xương đòn kép, IS có khả năng tăng tốc nhanh và xử lý nhạy bén, và hệ dẫn động tất cả các bánh tùy chọn mang lại sự yên tâm hơn. Cabin hiện đại có Apple CarPlay, Android Auto, điều khiển khí hậu cảm ứng và hỗ trợ lái xe an toàn chủ động. Lexus IS có danh tiếng tốt hơn về độ tin cậy so với một số đối thủ nhanh hơn và đẹp hơn.",},
            {"Lexus","UX","Đen","SUV","2.0L I4","Automatic","Gas","$34,025","image/car/Lexus/UX/","Khi nhiều nhà sản xuất ô tô chuyển trọng tâm sang xây dựng những chiếc SUV nhỏ và thực dụng, Lexus mang đến sự lựa chọn thoải mái và cao cấp với chiếc crossover Lexus UX. Chiếc SUV nhỏ nhất của thương hiệu hạng sang Nhật Bản thể hiện tất cả sự chú ý đến từng chi tiết và những tiện nghi cao cấp mà người TIỀN hàng mong đợi. Cùng với một cabin được trang bị tốt và hệ thống truyền động hybrid có sẵn, người lái xe sẽ có được các tính năng an toàn tiên tiến và khả năng xử lý an toàn.",},
            {"Lincoln","Aviator","Đen","SUV","3.0L V6 Turbo","Automatic","Gas","$52,195","image/car/Lincoln/Aviator/","Lincoln Aviator là chiếc SUV hạng trung của thương hiệu hạng sang. Nội thất ba hàng ghế rộng rãi và các tính năng an toàn cho người lái tiên tiến khiến Aviator trở thành sự lựa chọn thú vị cho các gia đình. Có nhiều tính năng tiêu chuẩn và có sẵn. Không gian hàng hóa và khả năng kéo là tuyệt vời. Người TIỀN có thể lựa chọn giữa động cơ V6 400 mã lực và động cơ plug-in hybrid mạnh mẽ hơn. Mặc dù mức tiết kiệm nhiên liệu thua kém một số đối thủ, Aviator vẫn hấp dẫn khi lái xe và có một chuyến đi êm ái.",},
            {"Lincoln","Corsair","Đen","SUV","2.0L I4 Turbo","Automatic","Gas","$37,100","image/car/Lincoln/Corsair/","Chiếc SUV nhỏ nhất của Lincoln, Corsair, mang đến sự thoải mái của thương hiệu Mỹ trong phân khúc xe hạng sang nhỏ gọn. Là một chiếc crossover đầy phong cách với hệ dẫn động tất cả các bánh, Lincoln Corsair có chiều cao hành trình cao giúp nó có tầm nhìn chỉ dẫn về con đường phía trước. Trang bị an toàn cho người lái là tiêu chuẩn và cabin rộng rãi của Corsair có công nghệ dễ sử dụng. Cùng với hai động cơ xăng êm ái, có sẵn một plug-in hybrid, với phạm vi chạy điện 15 dặm.",},
            {"Lincoln","Nautilus","Đen","SUV","2.0L I4 Turbo","Automatic","Gas","$42,935","image/car/Lincoln/Nautilus/","Là một chiếc SUV hạng trung mang linh hồn của một chiếc xe hơi sang trọng, Lincoln Nautilus mang đến vẻ đẹp sang trọng và trải nghiệm lái xe thư giãn trong một gói trang bị linh hoạt. Hành khách có thể thư giãn thoải mái và Lincoln còn trang bị công nghệ hỗ trợ người lái để tăng thêm sự an tâm. Trong khi đó, Nautilus có sẵn hệ dẫn động bốn bánh, không gian chở hàng rộng lớn và sức kéo phù hợp để xử lý các công việc hàng ngày trong cuộc sống.",},
            {"Lotus","Evora","Xam lam","Sedan","3.5L V6 S/C","Manual","Gas","$98,945","image/car/Lotus/Evora/","Lotus Evora là một chiếc xe thể thao động cơ đặt giữa hướng đến những người lái muốn một chiếc xe hiệu suất cao, độc đáo. Lotus có một di sản đua xe sâu sắc và được biết đến với việc chế tạo ra những chiếc xe đường trường có khả năng xử lý tuyệt vời. Evora có thiết kế kỳ lạ, động lực lái hấp dẫn và chất lượng hoàn thiện được chế tạo thủ công. Lotus lần đầu tiên ra mắt Evora cho năm mô hình 2011.",},
            {"Maserati","Ghibli","Đỏ","Sedan","3.0L V6","Automatic","Gas","$73,685","image/car/Maserati/Ghibli/","Maserati Ghibli là một chiếc sedan thể thao có một chút khác biệt. Trong khi một số đối thủ đang tập trung vào công nghệ lái xe và hệ thống hybrid nhẹ tinh vi, Maserati tiếp tục nhấn mạnh tinh thần lái xe thuần túy. Đạp ga và lắng nghe động cơ tăng áp kép tạo ra một bản hòa tấu của âm thanh xả. Ghibli mang đến cảm giác phấn khích thô sơ của một chiếc xe thể thao cổ điển của Ý, được gói gọn trong một chiếc sedan bốn cửa đầy phong cách và thoải mái.",},
            {"Maserati","Levante","Trắng","Sedan","3.0L V6 Turbo","Automatic","Gas","$75,985","image/car/Maserati/Levante/","Có rất nhiều sự cạnh tranh giữa các mẫu SUV hạng sang, và Maserati Levante tách mình ra khỏi nhóm với phong cách Ý và động lực lái thể thao. Chiếc SUV của Ý có khả năng vận hành như mong đợi, với công suất lên đến 580 mã lực và một nốt xả mạnh mẽ. Hệ thống treo khí nén cân bằng sự thoải mái và chắc chắn, liên tục điều chỉnh khi xe chuyển động. Các đối thủ có cabin được tinh chỉnh tốt hơn và nhiều không gian chở hàng hơn, nhưng ít đối thủ có được sự phù hợp của Levante.",},
            {"Maserati","Quattroporte","Trắng","Sedan","3.0L V6","Automatic","Gas","$101,485","image/car/Maserati/Quattroporte/","Maserati Quattroporte là mẫu sedan hạng sang cỡ lớn dành cho những ai yêu thích cảm giác lái. Chiếc xe cỡ lớn của Ý có khả năng tăng tốc nhanh nhờ các lựa chọn động cơ mạnh mẽ và nó cho thấy khả năng xử lý nhanh nhẹn của một chiếc xe nhỏ hơn nhiều. Bên trong cabin sang trọng, Maserati dành cho hành khách chất liệu ghế ngồi bọc da cao cấp và kệ hàng đầu. Một số đối thủ có nội thất hiện đại hơn, nhưng Quattroporte mang lại hiệu suất và cá tính độc đáo của Ý.",},
            {"Mazda","Mazda3","Đen","Sedan","2.0L I4","Automatic","Gas","$21,645","image/car/Mazda/Mazda 3/","Mazda Mazda3 là một chiếc sedan và hatchback nhỏ gọn với cabin cao cấp và khả năng vận hành thể thao hơn các đối thủ. Nó cung cấp ba lựa chọn động cơ và dẫn động cầu trước hoặc tất cả các bánh. Thân xe của Mazda3 trông giống như một chiếc sedan thể thao châu Âu, và nó có động lực lái phù hợp. Tiết kiệm nhiên liệu là tuyệt vời. Các thiết bị hỗ trợ an toàn hữu ích cho người lái là tiêu chuẩn, nhưng các ứng dụng điện thoại thông minh phổ biến và một số tiện nghi khác có trong các đối thủ chỉ đi kèm với các phụ kiện cao cấp hơn.",},
            {"Mazda","MX-5 Miata","Đen","Convertible","2.0L I4","Manual","Gas","$27,825","image/car/Mazda/MX-5 Miata/","Mazda MX-5 Miata là một chiếc xe mui trần hai cửa mang lại cảm giác lái thú vị với một mức giá phải chăng. Kích thước nhỏ và khả năng vận hành thể thao giúp tận dụng tối đa trọng lượng hạn chế thấp, và Miata mang lại khả năng tiết kiệm nhiên liệu ấn tượng. Một biến thể mui cứng RF có sẵn. Rất ít chiếc xe có thể sánh ngang với Miata về cảm giác lái tuyệt đối, nhưng nội thất nhỏ và không gian chứa đồ hạn chế đã cản trở tính thực dụng của nó như một tài xế hàng ngày. Công nghệ an toàn lái xe hiện đại là tiêu chuẩn.",},
            {"Mercedes-Benz","GLC","Xanh dương","SUV","2.0L I4 Turbo","Automatic","Gas","$44,250","image/car/Mercedes Benz/GLC/","Mercedes-Benz GLC là một chiếc SUV hạng sang nhỏ gọn pha trộn giữa cảm giác lái thư thái với khả năng vận hành thể thao. Cabin đầy phong cách của xe được bọc bằng vật liệu chất lượng cao và nhà sản xuất ô tô Đức chú ý đến từng chi tiết, tích hợp các công nghệ giải trí và an toàn cho người lái. GLC mang đến cảm giác cao cấp và độc quyền hơn nhiều đối thủ, và kiểu dáng cơ thể kiểu coupe đẹp mắt cũng có sẵn. Khách hàng có thể lựa chọn các mẫu AMG hiệu suất cao để có thêm nhiều niềm vui.",},
            {"Mercedes-Benz","GLE","Bạc","SUV","2.0L I4 Turbo","Automatic","Gas","$55,800","image/car/Mercedes Benz/GLE/","Mercedes-Benz GLE là một chiếc SUV hạng trung mang đến cho người TIỀN sự sang trọng hàng đầu trong một chiếc SUV thực dụng. Nó cân bằng tuyệt vời giữa một chuyến đi êm ái, yên tĩnh và khả năng xử lý như xe hơi. Cabin đạt tiêu chuẩn với nhiều tiện nghi và tính năng công nghệ, cùng các tùy chọn như hệ thống treo khí nén và động cơ hiệu suất AMG. GLE được thiết kế lại toàn bộ vào năm 2020. Giá khởi điểm khoảng 55.000 USD, đây là một trong những chiếc SUV gia đình phức tạp nhất trên thị trường.",},
            {"Mercedes-Benz","GLS","Đen","SUV","3.0L I6 Turbo","Automatic","Gas","$77,050","image/car/Mercedes Benz/GLS/","Một chuyến đi sang trọng và công nghệ tiên tiến khiến Mercedes-Benz GLS trở thành một trong những chiếc SUV cỡ lớn tốt nhất hiện có. Động cơ mạnh mẽ và khả năng vận hành thể thao khiến cảm giác lái trở nên hấp dẫn, trong khi cabin ba hàng ghế rộng rãi có chất lượng vật liệu hoàn hảo phù hợp với những chiếc sedan tốt nhất của nhà sản xuất ô tô Đức. Hệ thống treo khí nén, ghế thông gió, điều hướng, Apple CarPlay và kiểm soát khí hậu bốn vùng là tiêu chuẩn. Trang trí cực kỳ sang trọng và hiệu suất cao có sẵn.",},
            {"MINI","Clubman","Đen","Hatchbacks","2.0L I4 Turbo","Manual","Gas","$30,750","image/car/MINI/Clubman/","Yêu thích MINI Cooper, nhưng ước gì nó thực tế hơn một chút? MINI Clubman mở rộng chiều dài thân xe mang tính biểu tượng để có thêm không gian chở hành khách và hàng hóa, thay thế cửa nâng phía sau bằng 'cửa chuồng' chia đôi ở giữa. Tất cả các bánh cũng được cung cấp. Bạn vẫn có được tính cách lái xe vui nhộn của MINI, với hai tùy chọn động cơ tăng áp và khả năng xử lý nhanh nhẹn. Các đối thủ cung cấp các tính năng công nghệ tương tự với ít tiền hơn, nhưng không có đối thủ nào chia sẻ được sức hút của Clubman.",},
            {"MINI","Convertible","Bạc","Convertible","1.5L I3 Turbo","Manual","Gas","$28,250","image/car/MINI/Convertible/","MINI Convertible mang tất cả những nét quyến rũ và cảm giác lái phấn khích của mẫu xe hatchback MINI cổ điển và bổ sung thêm một chút không gian tự do. MINI Convertible bày tỏ lòng kính trọng với Vương quốc Anh theo vô số cách, từ đèn hậu Union Jack cho đến các sọc đua có sẵn. Bên dưới tất cả phong cách là một chiếc xe thực dụng đáng ngạc nhiên, với chỗ ngồi cho bốn người, dẫn động cầu trước và lên đến 36 mpg trên đường cao tốc.",},
            {"MINI","Countryman","Silver","SUV","1.5L I3 Turbo","Automatic","Gas","$29,950","image/car/MINI/Countryman/","MINI Countryman là một chiếc SUV cỡ nhỏ mang đến phong cách và tiện nghi cổ điển của Anh trong một gói dịch vụ mạo hiểm. Tất cả các bánh đều có sẵn, cũng như plug-in hybrid. Người mua có thể cá nhân hóa ngoại thất với các sọc đua, mái nhà màu tương phản, v.v. Cá tính này mở rộng đến cabin, nơi thiết kế quyến rũ đáp ứng sự thoải mái cao cấp. Và giống như tất cả MINI, Countryman rất thú vị khi lái xe, với sức mạnh turbo và khả năng xử lý nhanh nhẹn.",},
            {"Mitsubishi","Mirage","Silver","Car","1.2L I3","Manual","Gas","$14,990","image/car/Mitsubishi/Mirage/","Mitsubishi Mirage là một chiếc xe nhỏ gọn, có kích thước phù hợp với thành phố và khả năng tiết kiệm nhiên liệu tuyệt vời. Có sẵn dưới dạng hatchback 4 cửa hoặc sedan, Mirage có giá khởi điểm khoảng 14.000 USD và mang theo nhiều tính năng mà người đi làm sẽ đánh giá cao.",},
            {"Mitsubishi","Outlander","White","SUV","2.5L I4","Automatic","Gas","$26,990","image/car/Mitsubishi/Outlander/","Mitsubishi Outlander cung cấp chỗ ngồi cho bảy người và các tính năng thực tế với giá dưới 26.000 USD. Chế độ bảo hành kéo dài càng làm tăng thêm giá trị đặc biệt của Outlander, giúp nó nổi bật trong phân khúc SUV cỡ nhỏ. Là một trong số ít xe có kích thước như vậy với ba hàng ghế, Outlander nhanh nhẹn và dễ lái nhờ cảm giác lái êm ái và các nút điều khiển thân thiện với người dùng. Nó không thể thao hay sang trọng như một số mẫu xe khác, nhưng Outlander lại nổi trội như một chiếc xe gia đình đáng giá tiền.",},
            {"Mitsubishi","Outlander Sport","Red","SUV","2.0L I4","Automatic","Gas","$23,790","image/car/Mitsubishi/Outlander Sport/","Mitsubishi Outlander Sport là một chiếc crossover SUV nhỏ gọn đa dụng với kiểu dáng thể thao. Nó cung cấp nhiều tính năng tiêu chuẩn và bảo hành dài hạn với giá khoảng 23.000 đô la, khiến nó trở thành một trong những lựa chọn hợp lý nhất trong phân khúc của nó. Tuy nhiên, đây là một phân khúc đông đúc và một số đối thủ cung cấp nhiều tinh chỉnh nội thất hơn và các tính năng an toàn tiên tiến với giá cao hơn một chút. Nhưng thật khó để có thêm nội dung - và phong cách - với chi phí thấp của Outlander Sport.",},
            {"Porsche","Cayenne","Red","SUV","3.0L V6 Turbo","Automatic","Gas","$68,850","image/car/Porsche/Cayenne/","Với động cơ tăng áp mạnh mẽ, hệ thống treo đa liên kết nhanh nhẹn và công nghệ lấy cảm hứng từ cuộc đua, phần lớn bảng thông số kỹ thuật của Porsche Cayenne giống như của một chiếc xe thể thao đẳng cấp thế giới. Chiếc SUV hạng sang hạng trung không chỉ là một cú nổ để lái xe; nó không kém phần thoải mái khi vận chuyển thoải mái đến năm người một cách thoải mái, với một cabin rộng rãi được trang bị các vật liệu hàng đầu và công nghệ tiên tiến. Cayenne cũng có sẵn như một chiếc coupe bốn cửa kiểu dáng đẹp.",},
            {"Porsche","Macan","Sky Blue","SUV","2.0L I4 Turbo","Automatic","Gas","$53,450","image/car/Porsche/Macan/","Hiệu suất lái xe và công nghệ đua thương hiệu của Porsche đã tiến vào chiếc SUV cỡ nhỏ phổ biến của thương hiệu, Porsche Macan. Chiếc crossover nhỏ gọn có chỗ ngồi cho năm người trong một cabin thể hiện sự chú ý đến từng chi tiết và vật liệu trên kệ. Porsche mang đến cho khách hàng nhiều cơ hội về cấu hình. Cùng với việc là một trong những chiếc SUV thể thao nhất, Macan thực tế một cách đáng ngạc nhiên cho việc sử dụng hàng ngày.",},
            {"Porsche","Panamera","Blue","Sedan","3.0L V6 Turbo","Automatic","Gas","$88,550","image/car/Porsche/Panamera/","Panamera là chiếc sedan sang trọng hàng đầu của Porsche có công nghệ cao nhất, sự sang trọng và tiện nghi mà Porsche cung cấp. Panamera được cung cấp ở cả hai kiểu thân xe sedan và Sport Turismo và có sẵn trong một số hệ thống truyền động, bao gồm cả hybrid. Panamera là lựa chọn hàng đầu cho những ai đang tìm kiếm một chiếc xe sang trọng với kiểu dáng, sự chú ý đến từng chi tiết và khả năng vận hành của một chiếc xe thể thao Porsche.",},
            {"Ram","1500","Silver","Truck","3.6L V6","Automatic","Gas","$34,490","image/car/Ram/1500/","Ram 1500 là một chiếc xe bán tải cỡ lớn với mức độ tiện nghi hiếm có trong phân khúc. Hệ thống truyền động êm ái, hệ thống treo mềm và cabin yên tĩnh mang lại cho Ram cảm giác thư thái và cao cấp, khiến nó trở thành lựa chọn tuyệt vời cho những gia đình cần một chiếc xe chuyên dụng và những người lái xe đường dài. Nó rất khó, với sức kéo lên đến 12.750 pound và trọng tải 2.300 pound. Khả năng off-road rất tốt, đặc biệt là với trang trí TRX hỗ trợ bởi Hemi.",},
            {"Ram","2500","Brown","Truck","6.4L V8","Automatic","Gas","$36,390","image/car/Ram/2500/","Những chiếc xe bán tải hạng nặng có thể đảm đương những công việc khó khăn mà không loại xe nào có thể làm được, và Ram 2500 là một lựa chọn tuyệt vời trong phân khúc này. Hành khách sẽ yêu thích cabin rộng rãi và cảm giác lái êm ái cũng như màn hình cảm ứng 12 inch có sẵn. 2500 khe cắm ngay dưới Ram 3500 về khả năng, nhưng nó vẫn có thể kéo gần 20.000 lbs. Nó được cung cấp ở một số cấp độ trang trí được trang bị tốt, đánh bại các đối thủ về tính linh hoạt và giá trị.",},
            {"Ram","3500","Silver","Truck","6.4L V8","Automatic","Gas","$37,840","image/car/Ram/3500/","Ram 3500 là một chiếc xe bán tải hạng nặng, cỡ lớn được chế tạo cho nhiệm vụ chuyên chở voi ma mút, với sức kéo tối đa 37.100 lb tốt nhất phân khúc. Bánh sau kép có sẵn mang lại sự ổn định và phong cách không thể nhầm lẫn. Người mua có thể lựa chọn mẫu xe bốn cửa Mega Cab với không gian nội thất rộng lớn. Một chuyến đi êm ái và êm ái cùng với vật liệu cabin chất lượng cao khiến nó trở thành một trong những chiếc xe tải sang trọng nhất hiện nay.",},
            {"Subaru","Crosstrek","Yellow","SUV","2.0L H4","Manual","Gas","$23,295","image/car/Subaru/Crosstrek/","SUV trở nên phổ biến vào những năm 1990 như một sự thay thế chắc chắn cho sedan. Một số chiếc crossover ngày nay dường như đã không còn khát khao phiêu lưu nữa. Đối với Subaru Crosstrek thì không như vậy. Với hệ dẫn động tất cả các bánh tiêu chuẩn, một tư thế rộng rãi và thân xe chắc chắn, Crosstrek trông giống như nó đã sẵn sàng cho bất cứ điều gì. Cabin được trang bị đầy đủ chất liệu nhựa và vải bền. Công nghệ hiện đại như Apple CarPlay và Android Auto là tiêu chuẩn và có sẵn điểm phát sóng WiFi.",},
            {"Subaru","Forester","Red","SUV","2.5L H4","Automatic","Gas","$25,845","image/car/Subaru/Forester/","Những người mua sắm coi trọng thiết kế thực dụng và sự dẻo dai trong mọi thời tiết sẽ đánh giá cao Subaru Forester. Hệ dẫn động 4 bánh toàn thời gian và khoảng sáng gầm xe của chiếc SUV nhỏ gọn giúp người lái tự tin trong điều kiện lái xe có tuyết, trong khi cabin đơn giản mang đến nhiều không gian cho hành khách và tầm nhìn ra bên ngoài. Nó không phong cách hay thể thao như các đối thủ, cũng không cung cấp động cơ hybrid. Nhưng đối với những người cần các tính năng chắc chắn và tiện nghi chức năng, không cần tìm đâu xa.",},
            {"Subaru","Impreza","Deep Blue","Hatchbacks","2.0L H4","Manual","Gas","$19,720","image/car/Subaru/Impreza/","Subaru Impreza là một chiếc xe nhỏ gọn được xây dựng với tính năng lái xe trong mọi thời tiết. Trọng tâm thấp và hệ dẫn động tất cả các bánh tiêu chuẩn giúp tăng khả năng bám đường trên đường đất và đường cao tốc đầy tuyết. Có sẵn như một chiếc sedan hoặc hatchback, Impreza có nội thất rộng rãi và các vật liệu chất lượng cao giúp mang lại cho nó một chuyến đi êm ái. Bắt đầu dưới 19.000 đô la, Impreza là một người lái xe thực dụng hàng ngày với tinh thần mạo hiểm.",},
            {"Toyota","Highlander","Silver","SUV","3.5L V6","Automatic","Gas","$36,260","image/car/Toyota/Highlander/","Toyota Highlander là một trong những mẫu SUV hạng trung ba hàng ghế bán chạy nhất nhờ vào năng lực tổng thể, phong thái lái xe dễ chịu và danh tiếng lâu đời của Toyota về độ tin cậy. Kể từ khi được thiết kế lại vào năm 2020, Highlander thân thiện với gia đình cũng được biết đến với khả năng tiết kiệm nhiên liệu ấn tượng. Động cơ V6 tiêu chuẩn đứng đầu nhiều đối thủ cạnh tranh và Highlander Hybrid là mẫu SUV hạng trung tiết kiệm nhiên liệu nhất, dễ dàng làm lu mờ Ford Explorer Hybrid.",},
            {"Toyota","Sequoia","White","SUV","5.7L V8","Automatic","Gas","$51,765","image/car/Toyota/Sequoia/","Được đặt tên cho những cây cao nhất thế giới, Toyota Sequoia là một chiếc SUV cỡ lớn với khả năng vượt trội. Sequoia nâng các thành phần chắc chắn của nó từ xe bán tải Toyota Tundra, với kết cấu thân trên khung, động cơ V8 êm ái và hệ dẫn động bốn bánh tùy chọn. Cabin lớn thể hiện kỹ thuật thủ công đặc trưng của Toyota. Hỗ trợ an toàn cho người lái là tiêu chuẩn. Mặc dù nó không phải là hiện đại nhất, nhưng Sequoia đủ bền để đáp ứng nhu cầu của cuộc sống một cách dễ dàng.",},
            {"Toyota","Sienna","Red","Van","Hybrid 2.5L I4","Automatic","Hybrid","$35,635","image/car/Toyota/Sienna/","Toyota Sienna là một chiếc xe tải nhỏ có sức chứa từ bảy đến tám hành khách. Nội thất rộng rãi và các tính năng công nghệ tiêu chuẩn khiến nó trở thành sự lựa chọn tuyệt vời cho những gia đình muốn tìm kiếm không gian nội thất rộng rãi hơn một chiếc SUV. Mức tiết kiệm nhiên liệu ước tính là 36 mpg với động cơ hybrid tiêu chuẩn và hệ dẫn động tất cả các bánh có sẵn mang lại sự an tâm hơn trong điều kiện thời tiết khắc nghiệt. Toyota trang bị một bộ công nghệ an toàn cho người lái xe trên tất cả các xe Sienna mới.",},
            {"Volkswagen","Golf","Blue","HatchBacks","1.4L I4 Turbo","Manual","Gas","$24,190","image/car/Volkswagen/Golf/","Volkswagen Golf là một chiếc xe nhỏ gọn có giá cả phải chăng nhưng được hưởng lợi từ kỹ thuật đặc biệt của Đức. Nó lái giống như một chiếc xe đắt tiền hơn, với một chuyến đi không bị trượt mà vẫn mượt mà và ổn định ở tốc độ đường cao tốc. Động cơ bốn xi-lanh nhỏ của nó được tăng áp để tạo ra sự pha trộn giữa hiệu quả và tính thể thao, được cung cấp với hộp số sàn hoặc tự động. Nó có thể không có sức mạnh hoặc công nghệ của đối thủ, nhưng Golf cho thấy nó trả tiền để giữ mọi thứ đơn giản.",},
            {"Volkswagen","Jetta","Blue","Sedan","1.4L I4 Turbo","Manual","Gas","$19,990","image/car/Volkswagen/Jetta/","Volkswagen nhồi nhét những lợi ích của một chiếc sedan cỡ lớn vào một chiếc xe nhỏ gọn, phù hợp túi tiền. Chiếc sedan nhỏ có cabin và không gian chở hàng tuyệt vời và một chuyến đi tinh tế khó có thể tìm thấy trên một chiếc xe không sang trọng. Với giá dưới 20.000 đô la, người mua sẽ có được khả năng tiết kiệm nhiên liệu tuyệt vời từ hệ thống truyền động tăng áp. Một số đối thủ có kiểu dáng sáng tạo hơn và các tính năng tiêu chuẩn hào phóng. Tuy nhiên, Jetta vượt trội nhờ nền tảng bóng bẩy và nội thất rộng rãi.",},
            {"Volkswagen","Passat","Blue","Sedan","2.0L I4 Turbo","Automatic","Gas","$24,990","image/car/Volkswagen/Passat/","Volkswagen Passat là một chiếc sedan hạng trung với bản chất hợp lý. Nội thất lớn và các nút điều khiển thân thiện với người dùng giúp việc lái xe hàng ngày trở nên dễ dàng, được hỗ trợ bởi các thiết bị hỗ trợ an toàn và xử lý an toàn giúp người lái thêm yên tâm. Kỹ thuật và độ chính xác của Đức thể hiện qua độ ổn định của xe và sự tinh chỉnh trong cabin. Một số đối thủ trông thể thao hơn khi nhìn và lái xe, nhưng Passat cung cấp phương tiện di chuyển thực dụng cho gia đình với một mức giá đặc biệt.",},
            {"Volvo","XC40","White","SUV","2.0L I4 Turbo","Automatic","Gas","$34,795","image/car/Volvo/XC40/","Volvo XC40 là một chiếc SUV hạng sang cỡ nhỏ đầy phong cách và chất. Volvo từ lâu đã đặc biệt chú trọng đến an toàn và XC40 đi kèm với một số hỗ trợ người lái tiên tiến. Hệ thống truyền động hoàn toàn bằng điện có sẵn là một phần trong nỗ lực của nhà sản xuất ô tô Thụy Điển nhằm đáp ứng các tiêu chuẩn khí hậu toàn cầu. XC40 có ngoại thất hình khối đẹp mắt và cabin trang nhã. Một số đối thủ lái xe thể thao hơn, nhưng Volvo mang đến phong cách tinh tế và công nghệ tiên tiến.",},
            {"Volvo","XC60","Black","SUV","2.0L I4 Turbo","Automatic","Gas","$42,795","image/car/Volvo/XC60/","Volvo XC60 là một chiếc SUV hạng sang nhỏ gọn, đặt sự thoải mái và an toàn lên trên tính thể thao. Thiết kế tinh tế của Thụy Điển thể hiện qua nội thất da và gỗ tuyệt đẹp, và bên dưới bề mặt trang nhã, Volvo đã bao gồm nhiều thiết bị hỗ trợ an toàn cho người lái. Hệ thống truyền động plug-in hybrid có sẵn rất mạnh mẽ nhưng không cải thiện đáng kể hiệu suất nhiên liệu. Các đối thủ cung cấp nhiều tiện ích hơn và khả năng xử lý thể thao hơn, nhưng XC60 đặt tiêu chuẩn cho sự tinh tế.",},
            {"Volvo","XC90","Silver","SUV","2.0L I4 Turbo","Automatic","Gas","$50,095","image/car/Volvo/XC90/","Volvo XC90 là một trong những chiếc SUV hạng trung thanh lịch nhất trên thị trường. Phong cách Scandinavian hiện đại truyền vào tất cả các khía cạnh của XC90. Người mua có thể chọn trong số ba hệ thống truyền động, bao gồm một plug-in hybrid. Công nghệ trình điều khiển tiên tiến trở thành tiêu chuẩn và người mua sắm có thể bổ sung thêm tính năng lái bán tự động. Nội thất hiện đại và yên tĩnh, với chỗ ngồi cho tối đa bảy hành khách. Một số đối thủ cung cấp khả năng xử lý thể thao hơn, nhưng một số ít phù hợp với sự tinh chỉnh trong cabin của XC90.",},
            {"Acura","ILX","San Marino Red","Sedan","2.4L Inline-4 Gas","Automatic","Gas","$18,226","image/car/Acura/ILX/","Acura ILX là một chiếc sedan hạng sang cỡ nhỏ ưu tiên sự thoải mái hơn là tính thể thao. Dựa trên Honda Civic thực dụng, ILX cung cấp khả năng tiết kiệm nhiên liệu tuyệt vời cho việc lái xe hàng ngày. Cabin của nó có nhiều tính năng tiêu chuẩn và hệ thống an toàn cho người lái tiên tiến với mức giá khởi điểm thấp. Một ghế sau nhỏ và công nghệ già cỗi tụt hậu so với các đối thủ cùng phân khúc, nhưng giá trị vô địch của ILX và hệ thống truyền động tinh tế giúp nó trở thành một lựa chọn đáng mơ ước."},
            {"Acura","MDX","Modern Steel Metallic","SUV","3.5L V-6 Gas","Automatic","Gas","$30,189","image/car/Acura/MDX/","Acura MDX là mẫu SUV hạng sang ba hàng ghế nổi bật với công nghệ tiêu chuẩn. Bên dưới kiểu dáng cơ thể góc cạnh, MDX mang đậm chất thể thao, với động cơ V6 mạnh mẽ và khả năng xử lý nhanh nhẹn. Nhiều hỗ trợ lái xe an toàn đạt tiêu chuẩn. Một thiết kế lại năm 2022 đã mang lại cho MDX nhiều không gian hơn cho hành khách và hàng hóa. Cabin được trang bị đầy đủ các tính năng hàng đầu, như khả năng sạc không dây điện thoại trong khi sử dụng Apple CarPlay hoặc Android Auto."},
            {"Acura","NSX","Curva Red","Coupe","3.5L V-6 Hybrid Turbocharged","Automatic","Gas","$159,495","image/car/Acura/NSX/","Chiếc Acura NSX xuất hiện vào năm 1991, cho thấy Nhật Bản có thể chế tạo siêu xe nhanh như người Ý. Mười một năm sau khi gián đoạn, NSX đã trở lại với phiên bản năm 2016, lần này với hệ thống truyền động hybrid và hệ dẫn động bốn bánh toàn thời gian. Nó vẫn cung cấp khả năng tăng tốc nhanh như vũ bão của siêu xe, mặc dù công nghệ hiện đại nhất đã làm tăng giá thành. Acura NSX là sự lựa chọn tuyệt vời cho những ai tìm kiếm sự độc quyền và cảm giác lái thú vị."},
            {"Alfa Romeo","4C","Rosso Alfa","Coupe","1.8L Inline-4 Gas Turbocharged","Automatic","Gas","$54,900","image/car/Alfa Romeo/4C/","Alfa Romeo 4C là một chiếc xe mui trần thể thao với cách bố trí động cơ đặt giữa, khiến nó trở nên hấp dẫn đối với những người muốn có một chiếc xe nhỏ hiệu suất cao. 4C là một mô hình mới của Hoa Kỳ cho năm 2015 và nó đã nhận được các bản cập nhật kể từ đó. 4C là một chiếc Alfa Romeo cổ điển với thiết kế kiểu Ý đầy phong cách và khả năng xử lý nhanh nhẹn. Nó là một chiếc xe đường đua hoặc tàu tuần dương trên hẻm núi tuyệt vời, mặc dù hệ thống treo chắc chắn và tầm nhìn hạn chế khiến các đối thủ tốt hơn cho những chuyến đi dài hơn."},
            {"Alfa Romeo","Giulia","White","Coupe","2.0L Inline-4 Gas Turbocharged","Automatic","Gas","$24,495","image/car/Alfa Romeo/Giulia/","Những chiếc xe thể thao của Ý được biết đến với việc mang lại cảm giác lái thuần túy, mặc dù thường ở mức giá cao. Rất may, Alfa Romeo Giulia cung cấp một cách hợp lý - và thiết thực - để trải nghiệm những cảm giác mạnh như vậy hàng ngày. Chiếc sedan thể thao có giá khởi điểm khoảng 40.000 USD và bao gồm động cơ tăng áp mạnh mẽ, hệ dẫn động cầu sau và nội thất bọc da trang nhã. Khả năng xử lý rất nhanh nhẹn, khiến Giulia trở thành niềm vui khi lái xe trên những con đường ngoằn ngoèo."},
            {"Alfa Romeo","Stelvio","Gold","SUV","2.0L I4 Turbo","Automatic","Gas","$43,245","image/car/Alfa Romeo/Stelvio/","Thật khó để tìm thấy một nhà sản xuất ô tô hiện nay không bán một chiếc SUV. Điều đó cũng xảy ra đối với các nhà sản xuất xe thể thao. Một số mẫu xe crossover kết quả là thiếu tính năng khiến các thương hiệu trở nên nổi tiếng ngay từ đầu. Không phải như vậy đối với Alfa Romeo Stelvio, một chiếc SUV của Ý thành thạo trong việc tăng tốc và khắc góc. Cabin 5 người của Stelvio có kiểu dáng tập trung vào người lái và bọc da cao cấp. Nó cũng cung cấp các tùy chọn động cơ mạnh mẽ nhất trong cùng phân khúc."},
            {"Audi","A8","Phantom Black Pearl","L 4.2L","4.2L V-8 Gas","Automatic","Gas","$19,990","image/car/Audi/A8/","Là một chiếc sedan hạng sang cỡ lớn được chế tạo để chở bốn người với sự thoải mái hoàn toàn, Audi A8 tập hợp tất cả chuyên môn của nhà sản xuất ô tô Đức vào một cỗ máy. Được chế tạo từ các vật liệu chất lượng cao, A8 vẫn giữ được sự yên tĩnh khi ở tốc độ, nhờ hệ thống treo khí nén tự động cân bằng. Hành khách ngồi ở phía sau có không gian giống như xe limo và có thể ngả lưng bằng điện và mát-xa. Nó vẫn mang phong cách thể thao như một chiếc Audi, với động cơ tăng áp và hệ dẫn động tất cả các bánh."},
            {"Audi","S8","Phantom Black Pearl","Sedan","4.0L V-8 Gas Turbocharged","Automatic","Gas","$35,901","image/car/Audi/S8/","Audi S8 là một chiếc sedan hạng sang hiệu suất cao nhằm đưa hành khách đến đích với sự duyên dáng, thoải mái và tốc độ tối đa. Nó sử dụng công nghệ cao Audi A8 làm nền tảng và bổ sung động cơ hybrid V8 tăng áp kép, hệ thống treo thể thao, v.v. Tuy nhiên, từ bên ngoài, S8 duy trì một cấu hình thấp thanh lịch, ẩn bên dưới cơ bắp. Audi S8 được thiết kế lại hoàn toàn cho năm 2020 đánh dấu sự khởi đầu của thế hệ thứ tư."},
            {"Audi","TTS","Tango Red Metallic","Coupe","2.0L Inline-4 Gas Turbocharged","Automatic","Gas","$33,105","image/car/Audi/TTS/","Audi TTS là một chiếc xe thể thao dưới dạng coupe bốn chỗ hoặc roadster hai chỗ. Dựa trên TT, Audi lần đầu tiên ra mắt TTS vào năm 2008 và được thiết kế lại vào năm 2016. Nó thuộc thế hệ thứ hai."},
            {"BMW","5 Series","Jet Black","Sedan","2.0L Inline-4 Gas Turbocharged","Automatic","Gas","$30,999","image/car/BMW/5 Series/","BMW 5 Series từ lâu đã đặt tiêu chuẩn cho những chiếc sedan thể thao hạng trung, với khung gầm nhanh nhẹn và nội thất cao cấp. 5 Series thế hệ thứ bảy đi kèm với những nét hiện đại như các tính năng an toàn cho người lái tiên tiến và tùy chọn plug-in hybrid. Nó vẫn dễ dàng kết hợp giữa sự sang trọng với hiệu suất, đồng thời có khả năng hối hả dọc theo những con đường ngoằn ngoèo và chăm sóc hành khách. Cabin tinh tế đi kèm với nhiều tiện nghi tiêu chuẩn."},
            {"BMW","7 Series","Black Sapphire Metallic","Sedan","4.4L V-8 Gas Turbocharged","Automatic","Gas","$44,591","image/car/BMW/7 Series/","BMW 7 Series đại diện cho đỉnh cao chuyên môn về ô tô của nhà sản xuất Đức, một chiếc sedan hạng sang cỡ lớn được chế tạo bằng những vật liệu tốt nhất và các tính năng tiên tiến. Hành khách có được trải nghiệm di chuyển vượt trội hơn hẳn, với không gian trải dài và để những chiếc ghế sang trọng, âm thanh cao cấp và hệ thống khí hậu đa vùng giúp thư giãn sau một ngày dài. Khi đã đến lúc vui chơi, sự nhanh nhẹn mang tính thương hiệu của BMW sẽ tỏa sáng."},
            {"BMW","8 Series","Barcelona Blue Metallic","Coupe","4.4L V-8 Gas Turbocharged","Automatic","Gas","$88,935","image/car/BMW/8 Series/","BMW 8 Series là một chiếc coupe cỡ lớn cỡ lớn, được tạo ra cho những người muốn có một chiếc xe hiệu suất phong cách và sang trọng. Được đặt theo tên của Series 8 ban đầu được sản xuất từ năm 1989 đến năm 1999, phiên bản hoàn toàn mới ra mắt cho năm mô hình 2019."},
            {"Buick","Enclave","Ebony Twilight Metallic","SUV","3.6L V-6 Gas","Automatic","Gas","$26,997","image/car/Buick/Enclave/","Nhà sản xuất ô tô Mỹ cao cấp Buick được biết đến nhiều nhất với những chiếc sedan sang trọng của năm ngoái, nhưng người mua hàng nên chú ý đến Buick Enclave, một chiếc SUV ba hàng ghế cung cấp sự thoải mái đặc trưng trong một gói hiện đại. Dòng xe hàng đầu của thương hiệu có không gian nội thất rộng lớn và các nút điều khiển thân thiện với người dùng, với cảm giác lái như trên mây nhờ hệ thống treo được điều chỉnh mềm mại giúp loại bỏ các khuyết điểm trên đường. Một số vật liệu cabin có thể có chất lượng cao hơn so với giá tiền."},
            {"Buick","Encore GX","White Frost Tricoat","SUV","1.2L Inline-3 Gas Turbocharged","Automatic","Gas","$18,990","image/car/Buick/Encore GX/","Từng được biết đến với việc sản xuất những chiếc sedan cỡ lớn, Buick hiện chuyên sản xuất những chiếc SUV hạng sang và Buick Encore GX là mẫu xe bán chạy nhất của thương hiệu này. Nó cung cấp các tính năng cao cấp và một chuyến đi êm ái như Buicks của quá khứ trong một gói nhanh nhẹn và tiết kiệm nhiên liệu. Người lái xe sẽ đánh giá cao chiều cao hành trình tăng thêm so với một chiếc xe thông thường và hệ dẫn động bốn bánh tùy chọn để yên tâm hơn trong thời tiết khó chịu. Công nghệ an toàn cho người lái xe hiện đại giúp ngăn ngừa tai nạn trước khi chúng xảy ra."},
            {"Buick","Envision","Satin Steel Gray Metallic","SUV","2.5L Inline-4 Gas","Automatic","Gas","$18,843","image/car/Buick/Envision/","Buick Envision mang đến trải nghiệm lái sang trọng hơn so với những chiếc SUV cỡ nhỏ trung bình trong khi vẫn có giá cả phải chăng hơn hầu hết các đối thủ nhập khẩu. Các vật liệu cao cấp và tiện nghi sang trọng của cabin làm cho mỗi lần lái xe như một dịp. Động cơ tăng áp giúp tiết kiệm nhiên liệu cạnh tranh, đồng thời vận hành êm ái và yên tĩnh. Hệ thống hỗ trợ an toàn cho người lái tiên tiến và ghế sau rộng rãi khiến Envision trở thành một chiếc xe gia đình phù hợp."},
            {"Cadillac","CT5","Crystal White Tricoat","Sedan","2.0L Inline-4 Gas Turbocharged","Automatic","Gas","$34,990","image/car/Cadillac/CT5/","Cadillac mang hơi hướng Mỹ vào phân khúc sedan thể thao với CT5, một chiếc xe hạng trung pha trộn giữa khả năng vận hành tự tin, sự thoải mái trên đường dài và công nghệ trực quan. Hai hệ thống truyền động tăng áp giúp tăng tốc nhanh chóng và tạo cảm giác lái thú vị. Ngoài ra còn có các tính năng lái bán tự động cho phép xe tự lái trên đường cao tốc. Ít ai có thể sánh được với vẻ ngoài bắt mắt của CT5, cabin của nó mang đến không gian ấn tượng và sự yên tĩnh."},
            {"Cadillac","Escalade","Black Raven","SUV","6.2L V-8 Gas","Automatic","Gas","$51,899","image/car/Cadillac/Escalade/","Những người mua sắm đang nghiên cứu những mẫu xe SUV sang trọng, lớn nhất hiện có nên thêm Cadillac Escalade vào danh sách lựa chọn của họ. Ngoại thất hiện đại của Escalade kích thước đầy đủ ba hàng ghế quay đầu mọi lúc mọi nơi. Và bên dưới bề mặt, đó là một bữa tiệc cho các giác quan, với sức mạnh V8, bọc da dày dặn và công nghệ tiên tiến. Hệ dẫn động bốn bánh tùy chọn và sức kéo tối đa 8.200 pound có nghĩa là Cadillac có khả năng như nó được tinh chỉnh."},
            {"Cadillac","XT6","Stellar Black Metallic","SUV","3.6L V-6 Gas","Automatic","Gas","$48,590","image/car/Cadillac/XT6/","Mẫu crossover Cadillac XT6 chứng minh rằng bạn không cần một chiếc SUV cỡ lớn để trải nghiệm không gian ba hàng ghế và sự thoải mái. Kích thước thể thao giúp XT6 dễ dàng đưa trẻ đến trường và đỗ xe trong không gian nhỏ gọn, trong khi cabin sang trọng có thể chờ đợi những chuyến đi dài và đi đường trường. XT6 có sẵn với động cơ tăng áp bốn xi-lanh hoặc V6, với hệ dẫn động tất cả các bánh để có thêm sự an tâm. Các thiết bị hỗ trợ lái xe an toàn tiêu chuẩn giúp giữ an toàn cho mọi người khi tham gia giao thông."},
            {"Chevrolet","Malibu","Summit White","Sedan","1.5L Inline-4 Gas Turbocharged","Automatic","Gas","$16,555","image/car/Chevrolet/Malibu/","Với sự ra đi của Impala trong một thời gian dài, Chevrolet Malibu hiện là chiếc xe lớn nhất do nhà sản xuất ô tô danh tiếng của Mỹ sản xuất. Hệ thống truyền động tiết kiệm nhiên liệu và nội thất tiện nghi khiến chiếc sedan hạng trung đầy phong cách trở thành sự lựa chọn tuyệt vời cho nhiều người mua. Công nghệ lái xe dành cho thanh thiếu niên có sẵn cho phép cha mẹ đặt giới hạn tốc độ hoặc theo dõi lịch sử tuyến đường. Mặc dù nó đang bắt đầu thể hiện tuổi tác, Malibu vẫn là một sự lựa chọn cạnh tranh trong đẳng cấp của nó."},
            {"Chevrolet","Silverado 3500HD","Black","Truck","6.6L V-8 Diesel Turbocharged","Automatic","Gas","$49,995","image/car/Chevrolet/Silverado 3500HD/","Chevrolet Silverado 3500HD là chiếc xe có sức kéo mạnh nhất trong dòng xe của thương hiệu Mỹ, một chiếc xe bán tải hạng nặng có khả năng kéo lên đến 36.000 lbs. Nó đã sẵn sàng cho những công việc khó khăn nhất, cho dù đó là vận chuyển thiết bị xây dựng đến địa điểm làm việc hay vận chuyển RV gia đình cho một ngày cuối tuần phiêu lưu. Chevrolet cung cấp một số công nghệ kéo tốt nhất trong lĩnh vực kinh doanh, giúp cho việc kết nối xe kéo và điều động trở nên dễ dàng."},
            {"Chevrolet","Traverse","Silver Ice Metallic","SUV","3.6L V6","Automatic","Gas","$31,800","image/car/Chevrolet/Traverse/","Chevrolet Traverse 2021 là đối thủ cạnh tranh hàng đầu trong phân khúc crossover ba hàng ghế với không gian nội thất bên hông. Có sẵn với một trong những động cơ có mã lực cao nhất trong phân khúc, Traverse cơ sở là một món hời với mức giá khởi điểm dưới 30.000 USD. Nằm trong dòng sản phẩm Chevy giữa Chevrolet Equinox và Chevrolet Tahoe, Traverse là một trong những chiếc SUV hạng trung dài nhất với chiều dài hơn Toyota Highlander gần 10 inch. Nó cũng dài hơn các đối thủ cạnh tranh trực tiếp là Honda Pilot và Ford Explorer."},
            {"Chrysler","300","Maximum Steel Metallic Clearcoat","Sedan","3.6L V-6 Gas","Automatic","Gas","$24,000","image/car/Chyrsler/300/","Chrysler 300 cỡ lớn có kiểu dáng táo bạo gợi nhớ đến một chiếc sedan cổ điển của Mỹ. Dưới tấm kim loại tự tin, nền tảng dẫn động cầu sau của Chrysler mang đến cho chiếc 300 khả năng vận hành thể thao. Người lái có thể lựa chọn động cơ V6 êm ái hoặc Hemi V8. Hành khách có nhiều không gian ở cả hai hàng ghế và cabin vẫn yên tĩnh ở tốc độ cao. Công nghệ thông minh như Apple CarPlay và Android Auto được bao gồm trong khi hỗ trợ an toàn cho người lái xe."},
            {"Chrysler","Pacifica","Maximum Steel Metallic Clearcoat","Van","3.6L V-6 Gas","Automatic","Gas","$29,400","image/car/Chyrsler/Pacifica/","Chrysler Pacifica là một chiếc xe tải nhỏ cao cấp với tiện nghi và công nghệ phù hợp với các nhà lãnh đạo phân khúc hàng đầu. Vẻ ngoài bóng bẩy của nó trông thể thao và giống SUV. Nó vẫn là chiếc minivan duy nhất có động cơ hybrid, với phạm vi hoạt động hoàn toàn bằng điện là 30 km trước khi sử dụng bất kỳ loại khí nào. Hệ thống an toàn tiên tiến đạt tiêu chuẩn. Có rất nhiều tùy chọn công nghệ cao, chẳng hạn như camera trong cabin để kiểm tra ghế trẻ em quay mặt về phía sau và máy hút bụi trong trường hợp có bất kỳ sự cố tràn nào giữa chuyến đi."},
            {"Chrysler","Voyager","Granite Crystal Metallic Clearcoat","Van","3.6L V-6 Gas","Automatic","Gas","$24,995","image/car/Chyrsler/Voyager/","Bỏ qua các tính năng ưa thích của các đối thủ, Chrysler Voyager tập trung vào những gì thiết yếu trong phương tiện di chuyển gia đình - không gian và sự thoải mái. Với giá dưới 30.000 USD, nó mang đến một hệ thống truyền động V6 mượt mà, kiểu dáng thanh lịch và nội thất rộng lớn với các giải pháp lưu trữ mới. Rất ít xe tải nhỏ cung cấp loại giá trị như vậy, chứ đừng nói đến xe SUV ba hàng ghế. Voyager thiếu một số tính năng đẹp mắt, nhưng nội thất tinh tế khiến nó trở thành một đối thủ nặng ký về giá cả."},
            {"Dodge","Challenger","Pitch Black Clearcoat","Coupes","3.6L V-6 Gas","Automatic","Gas","$27,988","image/car/Dodge/Challenger/","Rất ít chiếc xe trên thị trường có được vẻ đẹp trường tồn của Dodge Challenger, một chiếc xe cơ bắp hiện đại được trang bị mã lực, sức hút và công nghệ để xử lý thế giới ngày nay. Dưới tấm kim loại điêu khắc, một cabin năm hành khách rộng rãi bao gồm các tiện nghi như hệ thống kiểm soát khí hậu hai vùng, cộng với sức chứa hàng hóa lớn. Cho dù đang đi du ngoạn hay vượt cạn ngay lập tức, các tính năng an toàn cho người lái tùy chọn của Challenger đều có mặt để trợ giúp."},
            {"Dodge","Durango","Granite Metallic Clearcoat","SUV","3.6L V-6 Gas","Automatic","Gas","$27,730","image/car/Dodge/Durango/","Đẹp trai và thể thao, Dodge Durango SUV có tiện ích ấn tượng và khả năng kéo tốt nhất trong phân khúc. Cabin ba hàng ghế của nó rộng rãi và thoải mái, và các tùy chọn bao gồm chức năng Apple CarPlay và Android Auto không dây. Trang bị SRT hiệu suất cao nhanh hơn nhiều xe thể thao. Một số mẫu SUV có khả năng tiết kiệm nhiên liệu tốt hơn và nhiều công nghệ an toàn hơn cho người lái, nhưng ít chiếc có thể sánh được với sức mạnh và tính cách thô sơ của Durango."},
            {"Dodge","Journey","Pitch Black Clearcoat","SUV","3.6L V-6 Gas","Automatic","Gas","$22,995","image/car/Dodge/Journey/","Dodge Journey là mẫu SUV hạng trung hướng đến người tiêu dùng đang tìm kiếm một chiếc xe ba hàng ghế với mức giá hợp lý. Dodge lần đầu tiên giới thiệu Journey với năm mô hình 2008, và nó vẫn đang ở thế hệ đầu tiên."},
            {"Fiat","124 Spider","Candy Apple Red","Convertible","1.4L I4 Turbo"," Automatic","Gas","$26,885","image/car/FIAT/124 Spider/","Fiat 124 là mẫu xe roadster nhắm tới những người muốn có 1 chiếc mui trần 2 chỗ ngồi với giá cả phải chăng. Tuy có nhiều điểm tương đồng với Mazda MX-5 Miata nhưng vẫn có 1 động cơ riêng và kiểu dáng Ý. Ra mắt lần đầu tiên vào năm 2017 và vẫn chỉ có 1 thế hệ."},
            {"Fiat","500L","Candy Apple Red","Hatchbacks","1.4L I4 Turbo"," Automatic","Gas","$25,070","image/car/FIAT/500L/","Fiat 500L là 1 chiếc xe hatchback 4 của nhỏ gọn hướng tới những người muốn 1 chiếc xe phong cách nhưng hưu dụng. 500L được Fiat ra mắt như là 1 phiên bản phóng to của mẫu 500 cho năm 2014"},
            {"Fiat","500X","Apple Red","SUV","1.3L I4 Turbo"," Automatic","Gas","$27,490","image/car/FIAT/500X/","Fiat 500X là 1 chiếc SUV cỡ nhỏ phong cách Ý. Với hệ thống dẫn động tất cả các bánh, thời tiết xấu không phải là nỗi lo khi lái chiếc xe này. Các cách sơn sẵn bao gồm Banco Gelato với Rosso Passione. Ở bên trong, 1 bảng điều khiển bao gồm các hệ thống hiện đại như Apple Carplay và Android Auto. Dù cho có ghế sau vừa vặn và giá khởi điểm khá là cao, nhưng sự phóng khoáng trong phong cách và tính linh hoạt của 500X khiến nó trở thành trải ngiệm đáng để thử qua."},
            {"Ford","Expedition","Color","SUV","3.5L V6 Turbo"," Automatic","Gas","$50,720","image/car/Ford/Expedition/","Một trong những chiếc SUV lớn nhất hiện tại trên thị trường. Ford Expedition phục vụ cho những người muốn có không gian hành khách tối đa. Nền tảng dựa trên xe tải cung cấp sự chắc chắn, trong khi bên trong có 8 chỗ ngồi thoải mái và bao gồm nhiều tiện nghi. Nhiều chiếc xe lớn trên thị trường phải vật lộn để tạo ra 1 không gian thoải mái mà Expedition tạo ra. Vẫn muốn thêm không gian? Đã có sẵn phiên bản mở rộng"},
            {"Ford","Mustang","Antimatter Blue Metallic","Coupe","2.3L I4 Turbo"," Automatic","Gas","$28,350","image/car/Ford/Mustang/","Khi ra mắt vào 5 thập kỉ trước, Ford Mustang đã thay đổi quan điểm về thế nào là 1 chiếc xe thể thao. Với 1 giá cả phải chăng, người lái có thể có phong cách và niềm vui khi lái mà tước đây học không có. Ngày nay, 1 chiếc fastback cơ bắp của Ford vẫn pha trộng giữa tính thể thao và giá trị, với mức giá khởi điểm dưới $30,000. Mustang đi kèm 1 động cơ mạnh mẽ với 1 loại các công nghệ đảm bảo an toàn cho người lái"},
            {"Ford","Super Duty F-450"," Lithium Gray Metallic","Truck"," Diesel 6.7L V8 Turbo"," image/car/Ford/Super Duty F-450/"," Diesel"," $52,105","Picture","Ford Super Duty F-450 là 1 chiếc xe bán tải phi thương mại lớn nhất cảu Ford và là 1 trong những chiếc xe vận hành tốt nhất trên thị trường. F-450 có sức kéo tốt nhất trong phân khúc, sức kéo lên đến 37.000 lbs khi được trang bị đúng cách. Bánh sau kép tiêu chuẩn giúp tăng độ ổn định khi chịu tải nặng. Bên trong cabin rộng rãi, hành khách được sử dụng công nghệ thân thiện với người dùng và các tính năng sang trọng sẵn có. Tuy đắt nhưng ít xe tải nào có thể sánh được với sức mạnh của F-450."},
            {"Genesis","G80","Vik Black","Sedan"," 2.5L I4 Turbo","Automatic","Gas"," $48,745","image/car/Genesis/G80/"," Genesis G80 là 1 chiếc sedan sang trọng mang đến sự thoải mái, độc quyền và hiệu suất hàng đầu với mức giá mà không đối thủ nào có thể sánh được. Bên dưới vẻ ngoài bóng bẩy là một cabin cực kỳ yên tĩnh và rộng rãi, với các vật liệu chất lượng cao xuyên suốt. Công nghệ tiêu chuẩn bao gồm đèn pha bốn LED, khả năng lái bán tự động và màn hình đa phương tiện 14,5 inch. Các tùy chọn bao gồm đỗ xe từ xa và ghế lái tiên tiến với các khoang khí bơm hơi."},
            {"Genesis","G90","Gold Coast Silver","Sedan"," 3.3L V6 Turbo","Automatic","Gas"," $73,225","image/car/Genesis/G90/"," Genesis G90 là một chiếc xe hạng sang cỡ lớn được thiết kế để mang đến một chuyến đi tuyệt vời cho cả người lái và hành khách. Với các lựa chọn động cơ V8 và tăng áp V6 mạnh mẽ, G90 có thể tăng tốc nhanh chóng trong khi vẫn giữ được một chuyến đi bình tĩnh và điềm đạm. Genesis G90 đã ra mắt lần đầu tiên tại Mỹ dưới dạng mô hình vào năm 2017. Nó có rất nhiều tiện nghi và công nghệ tiên tiến của những chiếc sedan siêu cao cấp hàng đầu khác, với mức giá thấp hơn nhiều."},
            {"Genesis","GV80","Gold Coast Silver","SUV"," 2.5L I4 Turbo","Automatic","Gas","Price","image/car/Genesis/GV80/"," Chiếc SUV đầu tiên của nhà sản xuất ô tô Genesis, GV80, là một chiếc SUV hạng trung sang trọng tập trung vào chất lượng và thiết kế sang trọng cao cấp. GV80 có giao diện và cảm giác cao cấp với mức giá thấp hơn một chút so với các đối thủ cạnh tranh của nó. Với một trong những danh sách hỗ trợ an toàn cho người lái xe phong phú nhất hiện có, chỗ ngồi hai hoặc ba hàng ghế và nhiều tiện nghi sang trọng, Genesis GV80 là 1 sự lựa chọn đáng cân nhắc.."},
            {"GMC","Acadia","Ebony Twilight Metallic","SUV"," 2.5L I4","Automatic","Gas"," $34,795","image/car/GMC/Acadia/"," Với ngoại thất sang trọng và cabin thoải mái, GMC Acadia có vẻ thu hút người mua hàng khỏi các đối thủ cạnh. Nội thất chất lượng của chiếc SUV hạng trung ba hàng ghế và khả năng xử lý tốt khiến nó có thể sử dụng được hàng ngày. Là người anh em họ gần gũi với Chevrolet Blazer, Acadia có nội thất cao cấp với các tính năng trực quan. Một số người mua sắm sẽ tìm kiếm khả năng tiết kiệm nhiên liệu tốt hơn hoặc nhiều không gian chở hàng hơn, nhưng GMC Acadia là một lựa chọn toàn diện"},
            {"GMC","Canyon","Summit White","Truck"," 3.6L V6","Automatic","Gas"," $39,395","image/car/GMC/Canyon/"," GMC Canyon mang đến sức mạnh, sự thoải mái và phong cách cho một chiếc xe bán tải hạng trung. Dùng khung sườn chắc chắn với Chevrolet Colorado, Canyon có vẻ ngoài cao cấp hơn và các tính năng cao cấp. Nó cung cấp một chuyến đi yên tĩnh và xử lý an toàn, với ba lựa chọn động cơ mạnh mẽ. Dù thiếu một số tính năng công nghệ tiên tiến tiêu chuẩn so với các đối thủ, nhưng trải nghiệm lái xe thoải mái và khả năng hàng đầu đã giúp chiếc xe không phải là 1 sự lựa chọn tồi."},
            {"GMC","Terain","Ebony Twilight Metallic","SUV","1.5L I4 Turbo","Automatic","Gas","$26,195","image/car/GMC/Terrain/","Những chiếc SUV nhỏ gọn đang là xu hướng ngày nay, và GMC Terrain do Mỹ sản xuất mang lại giá trị đáng kể cho hạng  mục với nhiều tiện nghi và mức giá khởi điểm thấp. Được xây dựng trên nền tảng mượt mà và tinh tế, nó mang đến sự lựa chọn động cơ tiết kiệm. Nội thất yên tĩnh cho 5 hành khách bao gồm công nghệ an toàn, Apple CarPlay và Android Auto. Chất lượng của một số vật liệu cabin thua các đối thủ hàng đầu, nhưng khả năng vận chuyển hàng hóa khổng lồ của Terrain khiến nó trở thành một lựa chọn đáng lưu tâm."},
            {"Honda","Clarity","Crimson Pearl"," Hybrids","Plug-In Hybrid 1.5L I4","Automatic","Plug-in Hybrid","$34,395","image/car/Honda/Clarity/","Theo đuổi mục tiêu tiết kiệm nhiên liệu tốt hơn, Honda Clarity là một trong những lựa chọn tương lai nhất hiện có. Được cung cấp trong các biến thể pin nhiên liệu plug-in hybrid hoặc hydro, Clarity mang đến tính linh hoạt chưa từng có. Kiểu dáng thân xe độc đáo của nó giúp cải thiện khả năng tiết kiệm xăng, đồng thời vận hành êm ái và thoải mái, ngay cả ở tốc độ đường cao tốc. Sự tinh tế và tính thực dụng mang tính thương hiệu của Honda thể hiện qua cabin. Một số thiết bị hỗ trợ lái xe an toàn là tiêu chuẩn."} ,
            {"Honda","Passport","Lunar Silver Metallic","SUV","3.5L V6","Automatic","Gas","$33,965","image/car/Honda/Passport/","Với nội thất rộng rãi, khoang chở hàng lớn, tính thể thao và chất lượng tuyệt vời kết hợp với độ tin cậy, Honda Passport 2021 5 chỗ ngồi là sự lựa chọn tuyệt vời cho các gia đình và những người thích phiêu lưu cuối tuần. Nó lọt vào hàng ngũ những chiếc Honda ở phía trên chiếc SUV cỡ nhỏ Honda CR-V phổ biến và bên dưới chiếc Honda Pilot 7 chỗ ngồi. Với hệ dẫn động tất cả các bánh có sẵn và khoảng sáng gầm 8,1 inch, Passport xử lý đường đất và các địa hình địa hình khác tốt hơn so với các đối thủ như Toyota Venza và Ford Edge. Đây cũng là một trong những chiếc crossover nhanh nhất trong phân khúc hạng trung, vì vậy việc tăng tốc trên đường cao tốc là điều dễ dàng. Passport cho cảm giác nhanh nhẹn mà không ảnh hưởng đến chất lượng xe, mặc dù các đối thủ cạnh tranh lớn hơn như Volkswagen Atlas và Chevrolet Blazer nhìn chung cung cấp những chuyến đi mượt mà hơn. Tiết kiệm xăng là một khía cạnh khác mà Passport chỉ ở mức trung bình."},
            {"Hondai","Pilot","Modern Steel Metallic","SUV","3.5L V6","Automatic","Gas","$33,725","image/car/Honda/Pilot/","Giống như hầu hết các mẫu crossover ba hàng ghế, Honda Pilot được thiết kế để xử lý mọi thứ một chút. Là chiếc xe lớn nhất của Honda, nó lọt vào hàng ngũ cao cấp hơn Honda Passport hai hàng ghế và Honda CR-V nhỏ gọn. Kích thước lớn hơn của Pilot cho phép có 8 chỗ ngồi và khu vực hàng hóa rộng rãi với kho chứa đồ dưới sàn. Khoang hành khách rộng rãi ở hàng đầu tiên và thứ hai, nhưng hàng thứ ba chật hẹp như hầu hết các loại xe ở hạng này. Động cơ V6 mạnh mẽ kết hợp với hộp số tự động chín cấp giúp Pilot tăng tốc nhanh hơn cả Toyota Highlander mạnh mẽ hơn. Tuy nhiên, vì Pilot được điều chỉnh chủ yếu để mang lại một chuyến đi êm ái, nó không mang tính thể thao. Khoang cabin yên tĩnh với chất liệu cao cấp nhưng thiết kế thiếu vẻ sang trọng gần giống các đối thủ như Kia Telluride và Mazda CX-9"},
            {"Huyndai","Elantra","Calypso Red","Sedan","2.0L I4","Automatic","Gas","$20,655","image/car/Hyundai/Elantra/","Hyundai Elantra là một chiếc sedan bốn cửa nhỏ gọn được tích hợp nhiều tính năng và giá trị vượt trội vào một thân hình đẹp như coupe. Với Apple CarPlay và Android Auto không dây tiêu chuẩn, hệ thống truyền động hybrid có sẵn và các tùy chọn như màn hình trình điều khiển kỹ thuật số, Elantra cung cấp công nghệ hiếm có ở mức giá này. Hyundai bao gồm bảo hành tiêu chuẩn về chiều dài đối với tất cả các xe ô tô mới của mình và các thiết bị hỗ trợ an toàn cho người lái xe tiêu chuẩn mang lại sự an tâm hơn."},
            {"Huyndai","Kona","Thunder Gray","SUV","2.0L I4","Automatic","Gas","$21,685","image/car/Hyundai/Kona/","Hyundai Kona là một chiếc crossover SUV cỡ nhỏ, phong cách, có khả năng tiết kiệm nhiên liệu tuyệt vời và nhiều tính năng tiêu chuẩn. Khả năng vận hành thể thao và động cơ tăng áp có sẵn giúp lái xe thú vị, trong khi một loạt các hỗ trợ an toàn chủ động mang lại sự an tâm hơn. Phiên bản chạy hoàn toàn bằng điện của Kona có phạm vi hoạt động ấn tượng là 258 dặm. Một số đối thủ rộng rãi hơn, nhưng sự pha trộn tuyệt vời của các thuộc tính với mức giá thấp khiến nó trở thành lựa chọn hàng đầu trong phân khúc."},
            {"Huyndai","Sonata","Calypso","Sedan","2.5L I4","Automatic","Gas","$23,819","image/car/Hyundai/Sonata/","Hyundai đã dành nhiều năm để xây dựng thương hiệu của mình để cạnh tranh với những thương hiệu phổ biến nhất, và Hyundai Sonata thế hệ mới nhất là ví dụ điển hình nhất cho những nỗ lực đó. Giá khởi điểm thấp và chế độ bảo hành hàng đầu của chiếc sedan hạng trung đã củng cố giá trị vượt trội của nó, trong khi kiểu dáng cao cấp, khả năng xử lý nhanh nhẹn và nội thất rộng rãi khiến nó trở thành một sự lựa chọn hấp dẫn hấp dẫn. Hỗ trợ an toàn tiên tiến là tiêu chuẩn, cũng như Apple CarPlay và Android Auto."},
            {"INFINITI","Q50","Candy Apple Red","Sedan","3.0L V6 Turbo","Automatic","Gas","$33,374","image/car/INFINITI/Q50/","Infiniti Q50 mang đến sự thoải mái và hiệu suất với mức giá thấp hơn so với các mẫu sedan thể thao cạnh tranh. Hình khối cơ bắp của Infiniti mang lại dáng vẻ hung hãn và động cơ tăng áp kép giúp người lái tự tin trên đường. Những người tìm kiếm sự thoải mái khi đi xe sẽ đánh giá cao nội thất rộng rãi. Apple CarPlay và Android Auto là tiêu chuẩn. Trong khi tiết kiệm nhiên liệu và công nghệ tụt hậu so với các đối thủ mới hơn, Q50 vẫn là một chiếc sedan có thẩm mỹ cao với một mức giá tuyệt vời."},
            {"INFINITI","QX50","Graphite Shadow","SUV","2.0L I4 Turbo","Automatic","Gas","$38,975","image/car/INFINITI/QX50/","Được thiết kế lại gần đây, Infiniti QX50 đã trở thành một trong những lựa chọn hiện đại và tiện nghi hơn trong phân khúc SUV hạng sang nhỏ gọn. Động cơ mạnh mẽ nhưng hiệu quả và công nghệ an toàn cho người lái tiêu chuẩn giúp QX50 trở thành một người lái xe thực dụng và tự tin hàng ngày. Cabin rộng rãi, với chỗ ngồi thoải mái tuyệt vời và một số không gian chở hàng tốt nhất trong phân khúc. Khả năng xử lý của nó không thú vị như các đối thủ, nhưng QX50 mang lại cảm giác thư giãn thoải mái cho bất kỳ chuyến đi nào."},
            {"INFINITI","QX60"," Hermosa Blue"," SUV","3.5L V6","Automatic","Gas","$45,375","image/car/INFINITI/QX60/","INFINITI QX60 là một chiếc crossover SUV sang trọng ba hàng ghế nhắm đến những người muốn có một chuyến đi giống như một chiếc ô tô trên một chiếc xe có thể chở tối đa bảy người cùng một lúc. Dựa trên Nissan Pathfinder, QX60 có rất nhiều độ chắc chắn và khả năng vượt mọi thời tiết. Cabin của nó sang trọng và rộng rãi, với ghế bọc giả da và ghế trước có sưởi. Lối vào không cần chìa khóa gần là tiêu chuẩn, cũng như cửa sổ trời chỉnh điện và cửa nâng điện"},
            {"Jaguar","F-PACE","Santorini Black","SUV","2.0L I4 Turbo","Automatic","Gas","$51,145","image/car/Jaguar/F-PACE/","Jaguar F-PACE là mẫu SUV hạng sang nhỏ gọn của hãng xe Anh quốc nổi tiếng với những mẫu xe thể thao đẹp mắt. Dưới lớp vật liệu chắc chắn, cabin rộng rãi của F-PACE dành cho năm người và hệ dẫn động bốn bánh trở nên hữu dụng cho các gia đình, trong khi động cơ mạnh mẽ và khả năng xử lý nhanh chóng mang lại cảm giác lái thú vị hơn so với các đối thủ. Apple CarPlay và Android Auto hiển thị trên màn hình cảm ứng 11,4 inch và khách hàng có thể cấu hình chiếc SUV của mình với các công nghệ và vật liệu nội thất cao cấp."},
            {"Jaguar","F-TYPE","Ocean Blue","Coupe","2.0L I4 Turbo","Automatic","Gas","$62,750","image/car/Jaguar/F-TYPE/","Jaguar F-Type là một chiếc xe thể thao hai chỗ ngồi đẹp và khỏe khoắn. Được biết đến với thiết kế đẹp mắt và nội thất xa hoa, F-Type là một trong những lựa chọn đẳng cấp nhất hiện nay. F-Type cạnh tranh ở nhiều cấp độ trong phân khúc xe thể thao cao cấp do có nhiều loại động cơ, trang bị và giá cả. F-Type ra mắt lần đầu vào năm 2014 và vẫn đang ở thế hệ đầu tiên."},
            {"Jaguar","XF","Silver Metallic","Sedan","2.0L I4 Turbo","Automatic","Gas","$52,250","image/car/Jaguar/XF/","Hãy nhìn vào biểu tượng của Jaguar, và rõ ràng thương hiệu này tượng trưng cho sự sang trọng và tốc độ. Với kiểu dáng hầm hố trông dữ tợn trên đường, Jaguar XF có tỷ lệ thể thao-sedan tạo sự cân bằng giữa sự thoải mái và khả năng tăng tốc. Nội thất kiểu dáng đẹp pha trộn giữa nét quyến rũ cổ kính của Anh và công nghệ tiên tiến. Với  động cơ mạnh mẽ và vẻ ngoài tinh tế của XF khiến nó trở thành một trong những lựa chọn hàng đầu trong phân khúc xe hạng sang, phân khúc hạng trung."},
            {"Jeep","Cherokee","Odsidian Black Metallic","SUV","2.4L I4","Automatic","Gas","$28,255","image/car/Jeep/Cherokee/","Những chiếc crossover nhỏ gọn đang là xu hướng thịnh hành ngày nay, nhưng hầu hết chỉ gồ ghề hơn một chút so với những chiếc xe dành cho người đi làm. Jeep Cherokee là một ngoại lệ được hoan nghênh, với cái tên được xây dựng dựa trên khả năng off-road của nó. Nó cũng có thể kéo tới 4.500 pound, thuộc loại hàng đầu. Khoang hành lý nhỏ, tiết kiệm nhiên liệu nhưng nội thất đi kèm nhiều tính năng tiêu chuẩn. Jeep Cherokee dành cho những tay lái muốn có một chiếc SUV cỡ nhỏ thoải mái trên đường trường hoặc địa hình."},
            {"Jeep","Gladiator","Sting-Gray Cleancoat","Truck","3.6L V6","Manual","Gas","$35,210","image/car/Jeep/Gladiator/","Jeep Gladiator là một chiếc xe bán tải hạng trung bốn cửa, có ngoại hình tuyệt vời và khả năng địa hình gồ ghề của Jeep Wrangler, cộng với sức kéo tối đa 7.760 pound và tải trọng 1.700 pound. Khi đường mòn kêu, Gladiator có hệ dẫn động bốn bánh tiêu chuẩn và công nghệ tùy chọn như khóa vi sai khóa trước và sau. Nó không tinh tế như các đối thủ, nhưng Gladiator đã thành công khi kết hợp khả năng huyền thoại của Jeep với các tiện ích bổ sung."},
            {"Jeep","Renegrade","Candy Apple Red","SUV","2.4L I4","Automatic","Gas","$24,345","image/car/Jeep/Renegade/","Những chiếc SUV cỡ nhỏ cung cấp nhiều thuộc tính mà người mua hàng mong muốn trong một gói hàng cỡ pint. Tuy nhiên, chúng thường không phải phù hợp với địa hình gồ ghề. Jeep Renegade thay đổi điều đó, với thân hình cao ráo, hình hộp và hệ dẫn động bốn bánh có sẵn. Các tính năng an toàn nâng cao cho người lái xe như hỗ trợ giữ làn đường là tiêu chuẩn, cũng như Apple CarPlay và Android Auto. Cabin thoải mái của Renegade rộng rãi ở cả hai hàng và có đủ chỗ chứa hàng cho những chuyến phiêu lưu cuối tuần."},
         };
    }
}