using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.SessionState;

namespace SellCar
{
    public class Global : System.Web.HttpApplication
    {

        protected void Application_Start(object sender, EventArgs e)
        {
            /*Đừng xoá
            List<Car> listNewCar = new List<Car>();
            listNewCar.Add(new Car("Ferrari", "F8", "Vàng", "Convertable", "3.9L V8 Turbo", "Automatic", "Gas", "$278,030", "/image/car/Ferrari/F8/", "Ferrari F8 là một cỗ máy hướng tới hiệu suất có nguồn gốc sâu xa từ xe đua và sự sang trọng. Thiết kế chắc chắn sẽ thu hút sự chú ý ở bất cứ đâu trong khi thẻ giá đảm bảo mức độ độc quyền nhất định."));
            listNewCar.Add(new Car("Ferrari","SF90 Stradale","Đỏ","Coupe","Plug-In Hybrid 4.0L V8 Turbo","Automatic","Premium Unleaded","$649,236","/image/car/Ferrari/SF90 Stradale/","Bản xem trước về thế hệ siêu xe tiếp theo sắp ra mắt tại Marinello, Ý, Ferrari SF90 Stradale là một sự tiến hóa trong cách điện có thể khai thác mã lực một cách liền mạch để nâng cao trải nghiệm lái xe. Đây là một trong những chiếc xe tăng tốc nhanh nhất và xử lý tốt nhất trên đường, với sức mạnh điện tức thời và hệ dẫn động 4 bánh bền bỉ. Nó không có tiếng xả ly kỳ như động cơ V12 cổ điển của Ferrari, và không gian chứa đồ nhỏ ngay cả theo tiêu chuẩn siêu xe. Bỏ qua những lời chỉ trích nhỏ, SF90 Stradale là một kỳ quan công nghệ đáng kinh ngạc và là một trong những chiếc xe đường trường nhanh nhất hiện có."));
            listNewCar.Add(new Car("Kia","Sedona","Đen","Hatchbacks","3.3L V6","Automatic","Regular Unleaded","$34,875","/image/car/KIA/Sedona/","Đối với những người TIỀN sắm trên thị trường cho một chiếc xe tải nhỏ thân thiện với ngân sách sẽ đánh giá cao Kia Sedona. Nó đi kèm với một động cơ V6 mạnh mẽ, mượt mà và dễ dàng chở tám người và đồ đạc của họ. Sedona có kiểu dáng bên ngoài đẹp trai mang lại vẻ thể thao hơn so với các đối thủ cạnh tranh, mặc dù cabin thông thường hơn. Tuy nhiên, nó rộng rãi và thoải mái, với các nút điều khiển dễ truy cập và nhiều tính năng tiêu chuẩn. Công nghệ ấn tượng nhất nằm trong trang trí SX đắt tiền, mức giá phù hợp với đề xuất giá trị của Sedona. Tuy nhiên, người lái xe sẽ đánh giá cao cửa trượt điện kép, ứng dụng điện thoại thông minh và phạm vi bảo hành đáng kể đi kèm với mỗi chiếc Sedona mới."));
            listNewCar.Add(new Car("Kia","Seltos","Gold","Hatchbacks","2.0L I4","Automatic","Gas","$23,165","/image/car/KIA/Seltos","Kia Seltos cung cấp một trong những thiết kế thời trang nhất trong danh mục của nó, và nền tảng hiện đại của nó đảm bảo một chuyến đi tuân thủ và thoải mái. Turbo tăng tốc nhanh chóng mà không ảnh hưởng nhiều đến hiệu quả và hệ thống hỗ trợ người lái gần như đạt tiêu chuẩn giúp mang lại sự an tâm hơn trước khi đường đi trở nên quá khó khăn. Một số đối thủ cạnh tranh cung cấp nội thất cao cấp hơn và tính linh hoạt, nhưng một số ít có thể phù hợp với sự hiện diện trên đường của Seltos về mức giá."));
            listNewCar.Add(new Car("Kia","Soul","Đỏ","Hatchbacks","2.0L I4","Manual","Gas","$18,765","/image/car/KIA/Soul","Kia Soul là sự lựa chọn tuyệt vời cho nhiều đối tượng khách hàng, từ gia đình nhỏ đến người đi làm, những người muốn một thứ gì đó khác biệt so với một chiếc xe cỡ nhỏ thông thường. Hệ thống truyền động hiệu quả của nó mang lại sức mạnh tốt và khả năng xử lý nhanh nhẹn, trong khi nội thất rộng rãi hơn các đối thủ và có nhiều tính năng sẵn có. Kiểu dáng cabin rất thú vị mà không ảnh hưởng đến tính thực dụng. Apple CarPlay và Android Auto là tiêu chuẩn, và hệ thống âm thanh Harman Kardon có sẵn có lưới loa LED. Với mức giá từ 17.500 đến 28.000 đô la, Soul là một lựa chọn tuyệt vời cho những người TIỀN sắm muốn có nhiều giá trị và điều đó được củng cố bởi thời gian bảo hành tiêu chuẩn kéo dài. Cơ sở trang trí thiếu nhiều tính năng, nhưng tất cả các trang trí khác đều được trang bị một cách hào phóng. Kia Soul mang đến nhiều điểm mạnh cho xe cỡ nhỏ trong một gói trang bị tổng thể quyến rũ, thú vị và đặc biệt."));
            listNewCar.Add(new Car("Land Rover","Defender","Trắng","SUV","2.0L I4 Turbo","Automatic","Gas","$47,774","/image/car/Land Rover/Defender/","Land Rover Defender vẫn là một trong những chiếc SUV đáng mơ ước nhất trong nhiều thập kỷ. Sự hiếm có của nó ở Hoa Kỳ chỉ làm tăng thêm sức hấp dẫn của nó. Vào năm 2020, Defender cuối cùng đã được phổ biến rộng rãi trên các bờ biển của Hoa Kỳ. Kiểu dáng nổi tiếng của nó truyền đạt những ý định chắc chắn của nó, không cái nào trong số đó đã biến mất theo chi phí của công nghệ. Trên thực tế, Defender mới là một kho tàng ma thuật cơ khí off-road, được trang bị hệ thống quản lý lực kéo thông minh nhất trên thị trường. Không giống như những chiếc Defenders trước đây, chiếc mới có bộ hệ thống an toàn cho người lái tiêu chuẩn và cabin yên tĩnh, tinh tế. Chuyến đi êm ái và thoải mái trên những con đường trải nhựa. Land Rover cung cấp một số trang bị và gói tùy chọn để đáp ứng nhu cầu của khách hàng, mặc dù những thứ đó có thể nhanh chóng tăng giá. Land Rover Defender tiếp tục là biểu tượng của sự nhạy bén và khám phá mọi địa hình, giờ đây đã có sẵn với nhiều cải tiến trên đường trường hơn bao giờ hết."));
            listNewCar.Add(new Car("Land Rover","Discovery","Đen xám","SUV","3.0L V6 S/C","Automatic","Gas","$53,650","/image/car/Land Rover/Discovery/","Land Rover Discovery là một chiếc SUV hạng trung hướng đến những người muốn một chiếc xe địa hình có khả năng vượt trội với nội thất ba hàng ghế sang trọng. Land Rover ban đầu ra mắt Discovery vào năm 1989. Thế hệ thứ 5 hiện tại bắt đầu với mẫu 2017."));
            listNewCar.Add(new Car("Land Rover","Discovery Sport","Đen xám","SUV","2.0L I4 Turbo","Automatic","Gas","$42,950","/image/car/Land Rover/Discovery Sport/","Land Rover nổi tiếng với việc chế tạo những chiếc SUV sang trọng chắc chắn, và Discovery Sport chắt lọc những đặc điểm này thành một gói nhỏ gọn, nhanh nhẹn. Khoảng sáng gầm xe cao và hệ dẫn động bốn bánh giúp xe vượt qua những cung đường khó hơn so với các đối thủ cạnh tranh, trong khi hành khách bên trong được tận hưởng một cabin rộng rãi với ghế da, hệ thống kiểm soát khí hậu hai vùng và công nghệ hỗ trợ người lái. Một số đối thủ lái xe thể thao hơn, nhưng ít đối thủ cung cấp sự pha trộn giữa các kỹ năng địa hình và địa hình của Land Rover."));
            listNewCar.Add(new Car("Lexus","ES","Xanh dương","Sedan","3.5L V6","Automatic","Gas","$41,025","image/car/Lexus/ES/","Lexus ES là một chiếc sedan hạng sang hạng trung với cảm giác lái êm ái và cabin sang trọng được xây dựng để tạo sự thoải mái. Ba loại động cơ có sẵn, bao gồm động cơ hybrid êm ái và nội thất lớn là một trong những động cơ tinh tế nhất trong phân khúc. Tất cả các thiết bị hỗ trợ lái xe an toàn chính đều là tiêu chuẩn và dễ sử dụng. Các trang bị phía trên có các tính năng như vô lăng sưởi và cốp điện rảnh tay. Trong khi nhiều đối thủ cố gắng trở thành những chiếc sedan thể thao, Lexus ES lại ưu tiên sự thoải mái tuyệt đối."));
            listNewCar.Add(new Car("Lexus","IS","Đỏ","Sedan","2.0L I4 Turbo","Automatic","Gas","$40,075","image/car/Lexus/IS/","Chiếc sedan hạng sang nhỏ gọn Lexus IS là một người lái xe vui vẻ, thiết thực hàng ngày. Với công suất lên đến 311 mã lực và hệ thống treo trước xương đòn kép, IS có khả năng tăng tốc nhanh và xử lý nhạy bén, và hệ dẫn động tất cả các bánh tùy chọn mang lại sự yên tâm hơn. Cabin hiện đại có Apple CarPlay, Android Auto, điều khiển khí hậu cảm ứng và hỗ trợ lái xe an toàn chủ động. Lexus IS có danh tiếng tốt hơn về độ tin cậy so với một số đối thủ nhanh hơn và đẹp hơn."));
            listNewCar.Add(new Car("Lexus","UX","Đen","SUV","2.0L I4","Automatic","Gas","$34,025","image/car/Lexus/UX/","Khi nhiều nhà sản xuất ô tô chuyển trọng tâm sang xây dựng những chiếc SUV nhỏ và thực dụng, Lexus mang đến sự lựa chọn thoải mái và cao cấp với chiếc crossover Lexus UX. Chiếc SUV nhỏ nhất của thương hiệu hạng sang Nhật Bản thể hiện tất cả sự chú ý đến từng chi tiết và những tiện nghi cao cấp mà người TIỀN hàng mong đợi. Cùng với một cabin được trang bị tốt và hệ thống truyền động hybrid có sẵn, người lái xe sẽ có được các tính năng an toàn tiên tiến và khả năng xử lý an toàn."));
            listNewCar.Add(new Car("Lincoln","Aviator","Đen","SUV","3.0L V6 Turbo","Automatic","Gas","$52,195","image/car/Lincoln/Aviator/","Lincoln Aviator là chiếc SUV hạng trung của thương hiệu hạng sang. Nội thất ba hàng ghế rộng rãi và các tính năng an toàn cho người lái tiên tiến khiến Aviator trở thành sự lựa chọn thú vị cho các gia đình. Có nhiều tính năng tiêu chuẩn và có sẵn. Không gian hàng hóa và khả năng kéo là tuyệt vời. Người TIỀN có thể lựa chọn giữa động cơ V6 400 mã lực và động cơ plug-in hybrid mạnh mẽ hơn. Mặc dù mức tiết kiệm nhiên liệu thua kém một số đối thủ, Aviator vẫn hấp dẫn khi lái xe và có một chuyến đi êm ái."));
            listNewCar.Add(new Car("Lincoln","Corsair","Đen","SUV","2.0L I4 Turbo","Automatic","Gas","$37,100","image/car/Lincoln/Corsair/","Chiếc SUV nhỏ nhất của Lincoln, Corsair, mang đến sự thoải mái của thương hiệu Mỹ trong phân khúc xe hạng sang nhỏ gọn. Là một chiếc crossover đầy phong cách với hệ dẫn động tất cả các bánh, Lincoln Corsair có chiều cao hành trình cao giúp nó có tầm nhìn chỉ dẫn về con đường phía trước. Trang bị an toàn cho người lái là tiêu chuẩn và cabin rộng rãi của Corsair có công nghệ dễ sử dụng. Cùng với hai động cơ xăng êm ái, có sẵn một plug-in hybrid, với phạm vi chạy điện 15 dặm."));
            listNewCar.Add(new Car("Lincoln","Nautilus","Đen","SUV","2.0L I4 Turbo","Automatic","Gas","$42,935","image/car/Lincoln/Nautilus/","Là một chiếc SUV hạng trung mang linh hồn của một chiếc xe hơi sang trọng, Lincoln Nautilus mang đến vẻ đẹp sang trọng và trải nghiệm lái xe thư giãn trong một gói trang bị linh hoạt. Hành khách có thể thư giãn thoải mái và Lincoln còn trang bị công nghệ hỗ trợ người lái để tăng thêm sự an tâm. Trong khi đó, Nautilus có sẵn hệ dẫn động bốn bánh, không gian chở hàng rộng lớn và sức kéo phù hợp để xử lý các công việc hàng ngày trong cuộc sống."));
            listNewCar.Add(new Car("Lotus","Evora","Xam lam","Sedan","3.5L V6 S/C","Manual","Gas","$98,945","image/car/Lotus/Evora/","Lotus Evora là một chiếc xe thể thao động cơ đặt giữa hướng đến những người lái muốn một chiếc xe hiệu suất cao, độc đáo. Lotus có một di sản đua xe sâu sắc và được biết đến với việc chế tạo ra những chiếc xe đường trường có khả năng xử lý tuyệt vời. Evora có thiết kế kỳ lạ, động lực lái hấp dẫn và chất lượng hoàn thiện được chế tạo thủ công. Lotus lần đầu tiên ra mắt Evora cho năm mô hình 2011."));
            listNewCar.Add(new Car("Maserati","Ghibli","Đỏ","Sedan","3.0L V6","Automatic","Gas","$73,685","image/car/Maserati/Ghibli/","Maserati Ghibli là một chiếc sedan thể thao có một chút khác biệt. Trong khi một số đối thủ đang tập trung vào công nghệ lái xe và hệ thống hybrid nhẹ tinh vi, Maserati tiếp tục nhấn mạnh tinh thần lái xe thuần túy. Đạp ga và lắng nghe động cơ tăng áp kép tạo ra một bản hòa tấu của âm thanh xả. Ghibli mang đến cảm giác phấn khích thô sơ của một chiếc xe thể thao cổ điển của Ý, được gói gọn trong một chiếc sedan bốn cửa đầy phong cách và thoải mái."));
            listNewCar.Add(new Car("Maserati","Levante","Trắng","Sedan","3.0L V6 Turbo","Automatic","Gas","$75,985","image/car/Maserati/Levante/","Có rất nhiều sự cạnh tranh giữa các mẫu SUV hạng sang, và Maserati Levante tách mình ra khỏi nhóm với phong cách Ý và động lực lái thể thao. Chiếc SUV của Ý có khả năng vận hành như mong đợi, với công suất lên đến 580 mã lực và một nốt xả mạnh mẽ. Hệ thống treo khí nén cân bằng sự thoải mái và chắc chắn, liên tục điều chỉnh khi xe chuyển động. Các đối thủ có cabin được tinh chỉnh tốt hơn và nhiều không gian chở hàng hơn, nhưng ít đối thủ có được sự phù hợp của Levante."));
            listNewCar.Add(new Car("Maserati","Quattroporte","Trắng","Sedan","3.0L V6","Automatic","Gas","$101,485","image/car/Maserati/Quattroporte/","Maserati Quattroporte là mẫu sedan hạng sang cỡ lớn dành cho những ai yêu thích cảm giác lái. Chiếc xe cỡ lớn của Ý có khả năng tăng tốc nhanh nhờ các lựa chọn động cơ mạnh mẽ và nó cho thấy khả năng xử lý nhanh nhẹn của một chiếc xe nhỏ hơn nhiều. Bên trong cabin sang trọng, Maserati dành cho hành khách chất liệu ghế ngồi bọc da cao cấp và kệ hàng đầu. Một số đối thủ có nội thất hiện đại hơn, nhưng Quattroporte mang lại hiệu suất và cá tính độc đáo của Ý."));
            listNewCar.Add(new Car("Mazda","Mazda3","Đen","Sedan","2.0L I4","Automatic","Gas","$21,645","image/car/Mazda/Mazda 3/","Mazda Mazda3 là một chiếc sedan và hatchback nhỏ gọn với cabin cao cấp và khả năng vận hành thể thao hơn các đối thủ. Nó cung cấp ba lựa chọn động cơ và dẫn động cầu trước hoặc tất cả các bánh. Thân xe của Mazda3 trông giống như một chiếc sedan thể thao châu Âu, và nó có động lực lái phù hợp. Tiết kiệm nhiên liệu là tuyệt vời. Các thiết bị hỗ trợ an toàn hữu ích cho người lái là tiêu chuẩn, nhưng các ứng dụng điện thoại thông minh phổ biến và một số tiện nghi khác có trong các đối thủ chỉ đi kèm với các phụ kiện cao cấp hơn."));
            listNewCar.Add(new Car("Mazda","MX-5 Miata","Đen","Convertible","2.0L I4","Manual","Gas","$27,825","image/car/Mazda/MX-5 Miata/","Mazda MX-5 Miata là một chiếc xe mui trần hai cửa mang lại cảm giác lái thú vị với một mức giá phải chăng. Kích thước nhỏ và khả năng vận hành thể thao giúp tận dụng tối đa trọng lượng hạn chế thấp, và Miata mang lại khả năng tiết kiệm nhiên liệu ấn tượng. Một biến thể mui cứng RF có sẵn. Rất ít chiếc xe có thể sánh ngang với Miata về cảm giác lái tuyệt đối, nhưng nội thất nhỏ và không gian chứa đồ hạn chế đã cản trở tính thực dụng của nó như một tài xế hàng ngày. Công nghệ an toàn lái xe hiện đại là tiêu chuẩn."));
            listNewCar.Add(new Car("Mercedes-Benz","GLC","Xanh dương","SUV","2.0L I4 Turbo","Automatic","Gas","$44,250","image/car/Mercedes Benz/GLC/","Mercedes-Benz GLC là một chiếc SUV hạng sang nhỏ gọn pha trộn giữa cảm giác lái thư thái với khả năng vận hành thể thao. Cabin đầy phong cách của xe được bọc bằng vật liệu chất lượng cao và nhà sản xuất ô tô Đức chú ý đến từng chi tiết, tích hợp các công nghệ giải trí và an toàn cho người lái. GLC mang đến cảm giác cao cấp và độc quyền hơn nhiều đối thủ, và kiểu dáng cơ thể kiểu coupe đẹp mắt cũng có sẵn. Khách hàng có thể lựa chọn các mẫu AMG hiệu suất cao để có thêm nhiều niềm vui."));
            listNewCar.Add(new Car("Mercedes-Benz","GLE","Bạc","SUV","2.0L I4 Turbo","Automatic","Gas","$55,800","image/car/Mercedes Benz/GLE/","Mercedes-Benz GLE là một chiếc SUV hạng trung mang đến cho người TIỀN sự sang trọng hàng đầu trong một chiếc SUV thực dụng. Nó cân bằng tuyệt vời giữa một chuyến đi êm ái, yên tĩnh và khả năng xử lý như xe hơi. Cabin đạt tiêu chuẩn với nhiều tiện nghi và tính năng công nghệ, cùng các tùy chọn như hệ thống treo khí nén và động cơ hiệu suất AMG. GLE được thiết kế lại toàn bộ vào năm 2020. Giá khởi điểm khoảng 55.000 USD, đây là một trong những chiếc SUV gia đình phức tạp nhất trên thị trường.")); 
            listNewCar.Add(new Car("Mercedes-Benz","GLS","Đen","SUV","3.0L I6 Turbo","Automatic","Gas","$77,050","image/car/Mercedes Benz/GLS/","Một chuyến đi sang trọng và công nghệ tiên tiến khiến Mercedes-Benz GLS trở thành một trong những chiếc SUV cỡ lớn tốt nhất hiện có. Động cơ mạnh mẽ và khả năng vận hành thể thao khiến cảm giác lái trở nên hấp dẫn, trong khi cabin ba hàng ghế rộng rãi có chất lượng vật liệu hoàn hảo phù hợp với những chiếc sedan tốt nhất của nhà sản xuất ô tô Đức. Hệ thống treo khí nén, ghế thông gió, điều hướng, Apple CarPlay và kiểm soát khí hậu bốn vùng là tiêu chuẩn. Trang trí cực kỳ sang trọng và hiệu suất cao có sẵn."));
            listNewCar.Add(new Car("MINI","Clubman","Đen","Hatchbacks","2.0L I4 Turbo","Manual","Gas","$30,750","image/car/MINI/Clubman/","Yêu thích MINI Cooper, nhưng ước gì nó thực tế hơn một chút? MINI Clubman mở rộng chiều dài thân xe mang tính biểu tượng để có thêm không gian chở hành khách và hàng hóa, thay thế cửa nâng phía sau bằng 'cửa chuồng' chia đôi ở giữa. Tất cả các bánh cũng được cung cấp. Bạn vẫn có được tính cách lái xe vui nhộn của MINI, với hai tùy chọn động cơ tăng áp và khả năng xử lý nhanh nhẹn. Các đối thủ cung cấp các tính năng công nghệ tương tự với ít tiền hơn, nhưng không có đối thủ nào chia sẻ được sức hút của Clubman."));
            listNewCar.Add(new Car("MINI","Convertible","Bạc","Convertible","1.5L I3 Turbo","Manual","Gas","$28,250","image/car/MINI/Convertible/","MINI Convertible mang tất cả những nét quyến rũ và cảm giác lái phấn khích của mẫu xe hatchback MINI cổ điển và bổ sung thêm một chút không gian tự do. MINI Convertible bày tỏ lòng kính trọng với Vương quốc Anh theo vô số cách, từ đèn hậu Union Jack cho đến các sọc đua có sẵn. Bên dưới tất cả phong cách là một chiếc xe thực dụng đáng ngạc nhiên, với chỗ ngồi cho bốn người, dẫn động cầu trước và lên đến 36 mpg trên đường cao tốc."));
            listNewCar.Add(new Car("MINI","Countryman","Silver","SUV","1.5L I3 Turbo","Automatic","Gas","$29,950","image/car/MINI/Countryman/","MINI Countryman là một chiếc SUV cỡ nhỏ mang đến phong cách và tiện nghi cổ điển của Anh trong một gói dịch vụ mạo hiểm. Tất cả các bánh đều có sẵn, cũng như plug-in hybrid. Người mua có thể cá nhân hóa ngoại thất với các sọc đua, mái nhà màu tương phản, v.v. Cá tính này mở rộng đến cabin, nơi thiết kế quyến rũ đáp ứng sự thoải mái cao cấp. Và giống như tất cả MINI, Countryman rất thú vị khi lái xe, với sức mạnh turbo và khả năng xử lý nhanh nhẹn."));
            listNewCar.Add(new Car("Mitsubishi","Mirage","Silver","Car","1.2L I3","Manual","Gas","$14,990","image/car/Mitsubishi/Mirage/","Mitsubishi Mirage là một chiếc xe nhỏ gọn, có kích thước phù hợp với thành phố và khả năng tiết kiệm nhiên liệu tuyệt vời. Có sẵn dưới dạng hatchback 4 cửa hoặc sedan, Mirage có giá khởi điểm khoảng 14.000 USD và mang theo nhiều tính năng mà người đi làm sẽ đánh giá cao."));
            listNewCar.Add(new Car("Mitsubishi","Outlander","White","SUV","2.5L I4","Automatic","Gas","$26,990","image/car/Mitsubishi/Outlander/","Mitsubishi Outlander cung cấp chỗ ngồi cho bảy người và các tính năng thực tế với giá dưới 26.000 USD. Chế độ bảo hành kéo dài càng làm tăng thêm giá trị đặc biệt của Outlander, giúp nó nổi bật trong phân khúc SUV cỡ nhỏ. Là một trong số ít xe có kích thước như vậy với ba hàng ghế, Outlander nhanh nhẹn và dễ lái nhờ cảm giác lái êm ái và các nút điều khiển thân thiện với người dùng. Nó không thể thao hay sang trọng như một số mẫu xe khác, nhưng Outlander lại nổi trội như một chiếc xe gia đình đáng giá tiền."));
            listNewCar.Add(new Car("Mitsubishi","Outlander Sport","Red","SUV","2.0L I4","Automatic","Gas","$23,790","image/car/Mitsubishi/Outlander Sport/","Mitsubishi Outlander Sport là một chiếc crossover SUV nhỏ gọn đa dụng với kiểu dáng thể thao. Nó cung cấp nhiều tính năng tiêu chuẩn và bảo hành dài hạn với giá khoảng 23.000 đô la, khiến nó trở thành một trong những lựa chọn hợp lý nhất trong phân khúc của nó. Tuy nhiên, đây là một phân khúc đông đúc và một số đối thủ cung cấp nhiều tinh chỉnh nội thất hơn và các tính năng an toàn tiên tiến với giá cao hơn một chút. Nhưng thật khó để có thêm nội dung - và phong cách - với chi phí thấp của Outlander Sport."));
            listNewCar.Add(new Car("Porsche","Cayenne","Red","SUV","3.0L V6 Turbo","Automatic","Gas","$68,850","image/car/Porsche/Cayenne/","Với động cơ tăng áp mạnh mẽ, hệ thống treo đa liên kết nhanh nhẹn và công nghệ lấy cảm hứng từ cuộc đua, phần lớn bảng thông số kỹ thuật của Porsche Cayenne giống như của một chiếc xe thể thao đẳng cấp thế giới. Chiếc SUV hạng sang hạng trung không chỉ là một cú nổ để lái xe; nó không kém phần thoải mái khi vận chuyển thoải mái đến năm người một cách thoải mái, với một cabin rộng rãi được trang bị các vật liệu hàng đầu và công nghệ tiên tiến. Cayenne cũng có sẵn như một chiếc coupe bốn cửa kiểu dáng đẹp."));
            listNewCar.Add(new Car("Porsche","Macan","Sky Blue","SUV","2.0L I4 Turbo","Automatic","Gas","$53,450","image/car/Porsche/Macan/","Hiệu suất lái xe và công nghệ đua thương hiệu của Porsche đã tiến vào chiếc SUV cỡ nhỏ phổ biến của thương hiệu, Porsche Macan. Chiếc crossover nhỏ gọn có chỗ ngồi cho năm người trong một cabin thể hiện sự chú ý đến từng chi tiết và vật liệu trên kệ. Porsche mang đến cho khách hàng nhiều cơ hội về cấu hình. Cùng với việc là một trong những chiếc SUV thể thao nhất, Macan thực tế một cách đáng ngạc nhiên cho việc sử dụng hàng ngày."));
            listNewCar.Add(new Car("Porsche","Panamera","Blue","Sedan","3.0L V6 Turbo","Automatic","Gas","$88,550","image/car/Porsche/Panamera/","Panamera là chiếc sedan sang trọng hàng đầu của Porsche có công nghệ cao nhất, sự sang trọng và tiện nghi mà Porsche cung cấp. Panamera được cung cấp ở cả hai kiểu thân xe sedan và Sport Turismo và có sẵn trong một số hệ thống truyền động, bao gồm cả hybrid. Panamera là lựa chọn hàng đầu cho những ai đang tìm kiếm một chiếc xe sang trọng với kiểu dáng, sự chú ý đến từng chi tiết và khả năng vận hành của một chiếc xe thể thao Porsche."));
            listNewCar.Add(new Car("Ram","1500","Silver","Truck","3.6L V6","Automatic","Gas","$34,490","image/car/Ram/1500/","Ram 1500 là một chiếc xe bán tải cỡ lớn với mức độ tiện nghi hiếm có trong phân khúc. Hệ thống truyền động êm ái, hệ thống treo mềm và cabin yên tĩnh mang lại cho Ram cảm giác thư thái và cao cấp, khiến nó trở thành lựa chọn tuyệt vời cho những gia đình cần một chiếc xe chuyên dụng và những người lái xe đường dài. Nó rất khó, với sức kéo lên đến 12.750 pound và trọng tải 2.300 pound. Khả năng off-road rất tốt, đặc biệt là với trang trí TRX hỗ trợ bởi Hemi."));
            listNewCar.Add(new Car("Ram","2500","Brown","Truck","6.4L V8","Automatic","Gas","$36,390","image/car/Ram/2500/","Những chiếc xe bán tải hạng nặng có thể đảm đương những công việc khó khăn mà không loại xe nào có thể làm được, và Ram 2500 là một lựa chọn tuyệt vời trong phân khúc này. Hành khách sẽ yêu thích cabin rộng rãi và cảm giác lái êm ái cũng như màn hình cảm ứng 12 inch có sẵn. 2500 khe cắm ngay dưới Ram 3500 về khả năng, nhưng nó vẫn có thể kéo gần 20.000 lbs. Nó được cung cấp ở một số cấp độ trang trí được trang bị tốt, đánh bại các đối thủ về tính linh hoạt và giá trị."));
            listNewCar.Add(new Car("Ram","3500","Silver","Truck","6.4L V8","Automatic","Gas","$37,840","image/car/Ram/3500/","Ram 3500 là một chiếc xe bán tải hạng nặng, cỡ lớn được chế tạo cho nhiệm vụ chuyên chở voi ma mút, với sức kéo tối đa 37.100 lb tốt nhất phân khúc. Bánh sau kép có sẵn mang lại sự ổn định và phong cách không thể nhầm lẫn. Người mua có thể lựa chọn mẫu xe bốn cửa Mega Cab với không gian nội thất rộng lớn. Một chuyến đi êm ái và êm ái cùng với vật liệu cabin chất lượng cao khiến nó trở thành một trong những chiếc xe tải sang trọng nhất hiện nay."));
            listNewCar.Add(new Car("Subaru","Crosstrek","Yellow","SUV","2.0L H4","Manual","Gas","$23,295","image/car/Subaru/Crosstrek/","SUV trở nên phổ biến vào những năm 1990 như một sự thay thế chắc chắn cho sedan. Một số chiếc crossover ngày nay dường như đã không còn khát khao phiêu lưu nữa. Đối với Subaru Crosstrek thì không như vậy. Với hệ dẫn động tất cả các bánh tiêu chuẩn, một tư thế rộng rãi và thân xe chắc chắn, Crosstrek trông giống như nó đã sẵn sàng cho bất cứ điều gì. Cabin được trang bị đầy đủ chất liệu nhựa và vải bền. Công nghệ hiện đại như Apple CarPlay và Android Auto là tiêu chuẩn và có sẵn điểm phát sóng WiFi."));
            listNewCar.Add(new Car("Subaru","Forester","Red","SUV","2.5L H4","Automatic","Gas","$25,845","image/car/Subaru/Forester/","Những người mua sắm coi trọng thiết kế thực dụng và sự dẻo dai trong mọi thời tiết sẽ đánh giá cao Subaru Forester. Hệ dẫn động 4 bánh toàn thời gian và khoảng sáng gầm xe của chiếc SUV nhỏ gọn giúp người lái tự tin trong điều kiện lái xe có tuyết, trong khi cabin đơn giản mang đến nhiều không gian cho hành khách và tầm nhìn ra bên ngoài. Nó không phong cách hay thể thao như các đối thủ, cũng không cung cấp động cơ hybrid. Nhưng đối với những người cần các tính năng chắc chắn và tiện nghi chức năng, không cần tìm đâu xa."));
            listNewCar.Add(new Car("Subaru","Impreza","Deep Blue","Hatchbacks","2.0L H4","Manual","Gas","$19,720","image/car/Subaru/Impreza/","Subaru Impreza là một chiếc xe nhỏ gọn được xây dựng với tính năng lái xe trong mọi thời tiết. Trọng tâm thấp và hệ dẫn động tất cả các bánh tiêu chuẩn giúp tăng khả năng bám đường trên đường đất và đường cao tốc đầy tuyết. Có sẵn như một chiếc sedan hoặc hatchback, Impreza có nội thất rộng rãi và các vật liệu chất lượng cao giúp mang lại cho nó một chuyến đi êm ái. Bắt đầu dưới 19.000 đô la, Impreza là một người lái xe thực dụng hàng ngày với tinh thần mạo hiểm."));
            listNewCar.Add(new Car("Toyota","Highlander","Silver","SUV","3.5L V6","Automatic","Gas","$36,260","image/car/Toyota/Highlander/","Toyota Highlander là một trong những mẫu SUV hạng trung ba hàng ghế bán chạy nhất nhờ vào năng lực tổng thể, phong thái lái xe dễ chịu và danh tiếng lâu đời của Toyota về độ tin cậy. Kể từ khi được thiết kế lại vào năm 2020, Highlander thân thiện với gia đình cũng được biết đến với khả năng tiết kiệm nhiên liệu ấn tượng. Động cơ V6 tiêu chuẩn đứng đầu nhiều đối thủ cạnh tranh và Highlander Hybrid là mẫu SUV hạng trung tiết kiệm nhiên liệu nhất, dễ dàng làm lu mờ Ford Explorer Hybrid."));
            listNewCar.Add(new Car("Toyota","Sequoia","White","SUV","5.7L V8","Automatic","Gas","$51,765","image/car/Toyota/Sequoia/","Được đặt tên cho những cây cao nhất thế giới, Toyota Sequoia là một chiếc SUV cỡ lớn với khả năng vượt trội. Sequoia nâng các thành phần chắc chắn của nó từ xe bán tải Toyota Tundra, với kết cấu thân trên khung, động cơ V8 êm ái và hệ dẫn động bốn bánh tùy chọn. Cabin lớn thể hiện kỹ thuật thủ công đặc trưng của Toyota. Hỗ trợ an toàn cho người lái là tiêu chuẩn. Mặc dù nó không phải là hiện đại nhất, nhưng Sequoia đủ bền để đáp ứng nhu cầu của cuộc sống một cách dễ dàng."));
            listNewCar.Add(new Car("Toyota","Sienna","Red","Van","Hybrid 2.5L I4","Automatic","Hybrid","$35,635","image/car/Toyota/Sienna/","Toyota Sienna là một chiếc xe tải nhỏ có sức chứa từ bảy đến tám hành khách. Nội thất rộng rãi và các tính năng công nghệ tiêu chuẩn khiến nó trở thành sự lựa chọn tuyệt vời cho những gia đình muốn tìm kiếm không gian nội thất rộng rãi hơn một chiếc SUV. Mức tiết kiệm nhiên liệu ước tính là 36 mpg với động cơ hybrid tiêu chuẩn và hệ dẫn động tất cả các bánh có sẵn mang lại sự an tâm hơn trong điều kiện thời tiết khắc nghiệt. Toyota trang bị một bộ công nghệ an toàn cho người lái xe trên tất cả các xe Sienna mới."));
            listNewCar.Add(new Car("Volkswagen","Golf","Blue","HatchBacks","1.4L I4 Turbo","Manual","Gas","$24,190","image/car/Volkswagen/Golf/","Volkswagen Golf là một chiếc xe nhỏ gọn có giá cả phải chăng nhưng được hưởng lợi từ kỹ thuật đặc biệt của Đức. Nó lái giống như một chiếc xe đắt tiền hơn, với một chuyến đi không bị trượt mà vẫn mượt mà và ổn định ở tốc độ đường cao tốc. Động cơ bốn xi-lanh nhỏ của nó được tăng áp để tạo ra sự pha trộn giữa hiệu quả và tính thể thao, được cung cấp với hộp số sàn hoặc tự động. Nó có thể không có sức mạnh hoặc công nghệ của đối thủ, nhưng Golf cho thấy nó trả tiền để giữ mọi thứ đơn giản."));
            listNewCar.Add(new Car());

            listNewCar.Add(new Car());
            listNewCar.Add(new Car());
            listNewCar.Add(new Car());
            */
        }

        protected void Session_Start(object sender, EventArgs e)
        {

        }

        protected void Application_BeginRequest(object sender, EventArgs e)
        {

        }

        protected void Application_AuthenticateRequest(object sender, EventArgs e)
        {

        }

        protected void Application_Error(object sender, EventArgs e)
        {

        }

        protected void Session_End(object sender, EventArgs e)
        {

        }

        protected void Application_End(object sender, EventArgs e)
        {

        }
    }
}